#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Nemla (نملة) - lightweight network reconnaissance tool.

Discover hosts, scan TCP ports, grab banners, guess the OS and generate
an HTML / JSON / CSV report.

Examples:
    python3 nemla.py                        # open the 3D interface
    sudo python3 nemla.py -t 192.168.1.0/24
    python3 nemla.py -t 192.168.1.1-50 -p 1-1000
    python3 nemla.py -t 192.168.1.10 --top-ports --lang ar
    python3 nemla.py -t scanme.example.org -p 22,80,443 --json out.json

Only scan systems and networks you own or have explicit permission to test.
"""
from __future__ import annotations

import argparse
import csv
import errno
import html
import io
import ipaddress
import json
import os
import re
import shutil
import socket
import subprocess
import sys
import threading
import time
from concurrent.futures import FIRST_COMPLETED, ThreadPoolExecutor, wait
from datetime import datetime

try:  # scapy is optional: it enables ARP discovery and raw-ICMP TTL probing
    from scapy.all import ARP, Ether, ICMP, IP, conf as scapy_conf, sr1, srp

    scapy_conf.verb = 0
    HAVE_SCAPY = True
except Exception:  # pragma: no cover - depends on the environment
    HAVE_SCAPY = False

__version__ = "1.1.0"

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TOP_PORTS = sorted({
    21, 22, 23, 25, 53, 80, 110, 111, 135, 139, 143, 443, 445, 465, 587,
    993, 995, 1080, 1433, 1521, 1723, 2049, 3128, 3306, 3389, 5432, 5900,
    5985, 6000, 6379, 8000, 8080, 8081, 8443, 8888, 9200, 11211, 27017,
})

COMMON_SERVICE_NAMES = {
    21: "FTP", 22: "SSH", 23: "Telnet", 25: "SMTP", 53: "DNS", 80: "HTTP",
    110: "POP3", 111: "RPCBind", 135: "MS-RPC", 139: "NetBIOS", 143: "IMAP",
    443: "HTTPS", 445: "SMB", 465: "SMTPS", 587: "SMTP-Submission",
    993: "IMAPS", 995: "POP3S", 1080: "SOCKS", 1433: "MSSQL", 1521: "Oracle",
    1723: "PPTP", 2049: "NFS", 3128: "Squid", 3306: "MySQL", 3389: "RDP",
    5432: "PostgreSQL", 5900: "VNC", 5985: "WinRM", 6000: "X11",
    6379: "Redis", 8000: "HTTP-Alt", 8080: "HTTP-Proxy", 8081: "HTTP-Alt",
    8443: "HTTPS-Alt", 8888: "HTTP-Alt", 9200: "Elasticsearch",
    11211: "Memcached", 27017: "MongoDB",
}

HTTP_PORTS = {80, 3128, 8000, 8080, 8081, 8888}
TLS_PORTS = {443, 465, 636, 993, 995, 8443}
DISCOVERY_PORTS = (80, 443, 22, 445, 3389, 135, 8080)

# connect_ex results that prove a host is alive (open port, or a RST reply)
_ALIVE_ERRNOS = {0, errno.ECONNREFUSED, 10061}

# ---------------------------------------------------------------------------
# Translations
# ---------------------------------------------------------------------------

STRINGS = {
    "en": {
        "notice": "Use only on networks you own or are authorized to test.",
        "arp_start": "Discovering hosts via ARP ({n} addresses)...",
        "probe_start": "Discovering hosts via ICMP + TCP ({n} addresses)...",
        "arp_permission": "ARP scan needs elevated privileges (try sudo). Falling back to ICMP/TCP.",
        "arp_failed": "ARP scan failed ({err}). Falling back to ICMP/TCP.",
        "found": "Discovered {n} host(s)",
        "no_hosts": "No hosts discovered. Check connectivity, or use --no-ping if the target blocks ping.",
        "skip_discovery": "Discovery skipped, treating all {n} target(s) as up.",
        "port_count": "Scanning {n} port(s) per host",
        "scanning": "Scanning {ip} ...",
        "host_done": "-> {n} open port(s) | OS: {os}",
        "done": "Scan finished in {sec:.1f}s",
        "interrupted": "Interrupted - saving partial results.",
        "saved": "{kind} saved: {path}",
        "invalid_target": "Invalid target: {err}",
        "invalid_ports": "Invalid ports: {err}",
        "too_many": "Target has {n} addresses, above the --max-hosts limit ({limit}). Raise --max-hosts if you really mean it.",
        "ipv6": "IPv6 targets are not supported yet.",
        "bad_range": "Bad IP range: {spec}",
        "cannot_resolve": "cannot resolve '{spec}'",
        "os_unknown": "Unknown",
        "os_skipped": "Skipped",
        "os_rdp_smb": "Windows (RDP/SMB detected)",
        "os_ssh": "Linux / Unix (SSH detected)",
        "r_title": "Nemla Recon Report",
        "r_target": "Target",
        "r_date": "Scan date",
        "r_duration": "Duration",
        "r_hosts": "Hosts discovered",
        "r_open": "Open ports",
        "r_scanned": "Ports scanned per host",
        "r_port": "Port",
        "r_service": "Service",
        "r_banner": "Banner",
        "r_no_ports": "No open ports in the scanned range",
        "r_no_hosts": "No hosts to display",
        "r_active": "Active",
        "r_footer": "Generated by Nemla v{ver} - responsible use only, on networks you are authorized to scan",
        "desc": "Nemla - lightweight network reconnaissance tool",
    },
    "ar": {
        "notice": "استخدمها فقط على شبكات تملكها أو لديك تصريح صريح لفحصها.",
        "arp_start": "اكتشاف الأجهزة عبر ARP ({n} عنوان)...",
        "probe_start": "اكتشاف الأجهزة عبر ICMP + TCP ({n} عنوان)...",
        "arp_permission": "فحص ARP يحتاج صلاحيات أعلى (جرّب sudo). سيتم التحويل إلى ICMP/TCP.",
        "arp_failed": "فشل فحص ARP ({err}). سيتم التحويل إلى ICMP/TCP.",
        "found": "تم اكتشاف {n} جهاز",
        "no_hosts": "لم يتم اكتشاف أي جهاز. تأكد من الاتصال، أو استخدم --no-ping إذا كان الهدف يحجب ping.",
        "skip_discovery": "تم تخطي الاكتشاف، سيتم اعتبار الأهداف ({n}) كلها شغّالة.",
        "port_count": "فحص {n} منفذ لكل جهاز",
        "scanning": "فحص {ip} ...",
        "host_done": "-> {n} منفذ مفتوح | نظام التشغيل: {os}",
        "done": "اكتمل الفحص خلال {sec:.1f} ثانية",
        "interrupted": "تم الإيقاف - سيتم حفظ النتائج الجزئية.",
        "saved": "تم حفظ {kind}: {path}",
        "invalid_target": "هدف غير صالح: {err}",
        "invalid_ports": "منافذ غير صالحة: {err}",
        "too_many": "الهدف فيه {n} عنوان، وهذا أكبر من حد --max-hosts ({limit}). ارفع الحد إذا كنت متأكداً.",
        "ipv6": "عناوين IPv6 غير مدعومة حالياً.",
        "bad_range": "نطاق IP غير صالح: {spec}",
        "cannot_resolve": "تعذّر حل الاسم '{spec}'",
        "os_unknown": "غير معروف",
        "os_skipped": "تم التخطي",
        "os_rdp_smb": "Windows (تم اكتشاف RDP/SMB)",
        "os_ssh": "Linux / Unix (تم اكتشاف SSH)",
        "r_title": "تقرير نملة",
        "r_target": "الهدف",
        "r_date": "تاريخ الفحص",
        "r_duration": "المدة",
        "r_hosts": "أجهزة مكتشفة",
        "r_open": "منافذ مفتوحة",
        "r_scanned": "منفذ تم فحصه لكل جهاز",
        "r_port": "المنفذ",
        "r_service": "الخدمة",
        "r_banner": "Banner",
        "r_no_ports": "لا توجد منافذ مفتوحة ضمن النطاق المفحوص",
        "r_no_hosts": "لا توجد أجهزة لعرضها",
        "r_active": "شغّال",
        "r_footer": "تم توليده بواسطة نملة (Nemla) v{ver} - استخدام مسؤول فقط على شبكات مصرّح بفحصها",
        "desc": "نملة - أداة استطلاع شبكة خفيفة",
    },
}

_LANG = "en"
_PRINT_LOCK = threading.Lock()
_LOG_SINK = None  # optional callable(str): the 3D interface mirrors log lines here


def t(key: str, **kw) -> str:
    """Translate `key` into the active language (falls back to English)."""
    text = STRINGS.get(_LANG, {}).get(key) or STRINGS["en"][key]
    return text.format(**kw) if kw else text


def log(msg: str) -> None:
    with _PRINT_LOCK:
        try:
            print(f"[{datetime.now():%H:%M:%S}] {msg}", flush=True)
        except (OSError, ValueError):  # no console (desktop launcher) or a closed stream
            pass
    sink = _LOG_SINK
    if sink is not None:
        sink(msg)


LOGO_LINES = (
    "██      ██  ██████████  ██      ██  ██            ██████  ",
    "████    ██  ██          ████  ████  ██          ██      ██",
    "██  ██  ██  ████████    ██  ██  ██  ██          ██████████",
    "██    ████  ██          ██      ██  ██          ██      ██",
    "██      ██  ██████████  ██      ██  ██████████  ██      ██",
)
# amber -> ember -> deep ember, top to bottom (the Nemla palette)
LOGO_GRADIENT = ((255, 196, 107), (255, 152, 48), (255, 122, 26), (240, 92, 18), (232, 70, 12))


def fancy_output_ok() -> bool:
    """True when stdout is a UTF-8 terminal that can show the block-letter logo."""
    stream = sys.stdout
    try:
        tty = stream.isatty()
    except (AttributeError, ValueError):
        tty = False
    encoding = (getattr(stream, "encoding", "") or "").lower()
    return tty and "utf" in encoding and os.environ.get("TERM") != "dumb"


def banner_text(color: bool = True) -> str:
    """The startup banner: block-letter NEMLA in the ember gradient."""
    lines = [""]
    for row, rgb in zip(LOGO_LINES, LOGO_GRADIENT):
        lines.append("  " + (f"\x1b[38;2;{rgb[0]};{rgb[1]};{rgb[2]}m{row}\x1b[0m" if color else row))
    dim, reset = ("\x1b[38;2;162;171;190m", "\x1b[0m") if color else ("", "")
    lines += [
        "",
        f"  {dim}نملة  ·  Discover · Scan · Fingerprint · Report  ·  v{__version__}{reset}",
        f"  {dim}{t('notice')}{reset}",
        "",
    ]
    return "\n".join(lines)


def print_banner() -> None:
    if fancy_output_ok():
        print(banner_text(color="NO_COLOR" not in os.environ))
    else:
        print(f"\n  \U0001F41C  Nemla / نملة  v{__version__}  -  Network Recon")
        print(f"  {t('notice')}\n")


# ---------------------------------------------------------------------------
# Target and port parsing
# ---------------------------------------------------------------------------

def parse_targets(spec: str, max_hosts: int = 1024) -> list:
    """Turn a target spec into a list of IPv4 address strings.

    Supported: single IP, hostname, CIDR (10.0.0.0/24), full range
    (10.0.0.1-10.0.0.50) and short range (10.0.0.1-50).
    """
    spec = spec.strip()
    if not spec:
        raise ValueError(t("bad_range", spec=spec))

    if "/" in spec:
        net = ipaddress.ip_network(spec, strict=False)
        if net.version != 4:
            raise ValueError(t("ipv6"))
        if net.num_addresses > max_hosts:
            raise ValueError(t("too_many", n=net.num_addresses, limit=max_hosts))
        hosts = list(net.hosts()) or list(net)
        return [str(h) for h in hosts]

    m = re.fullmatch(r"(\d+\.\d+\.\d+\.\d+)-(\d+(?:\.\d+\.\d+\.\d+)?)", spec)
    if m:
        first = ipaddress.ip_address(m.group(1))
        end = m.group(2)
        if "." not in end:  # short form: only the last octet changes
            prefix = m.group(1).rsplit(".", 1)[0]
            last = ipaddress.ip_address(f"{prefix}.{end}")
        else:
            last = ipaddress.ip_address(end)
        if last < first:
            raise ValueError(t("bad_range", spec=spec))
        count = int(last) - int(first) + 1
        if count > max_hosts:
            raise ValueError(t("too_many", n=count, limit=max_hosts))
        return [str(ipaddress.ip_address(int(first) + i)) for i in range(count)]

    try:
        addr = ipaddress.ip_address(spec)
    except ValueError:
        try:  # maybe a hostname
            return [socket.gethostbyname(spec)]
        except OSError:
            raise ValueError(t("cannot_resolve", spec=spec)) from None
    if addr.version != 4:
        raise ValueError(t("ipv6"))
    return [str(addr)]


def parse_ports(spec: str) -> list:
    """Parse '22', '22,80,443' or '1-1000' (and mixes) into sorted ports."""
    ports = set()
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            a, b = part.split("-", 1)
            lo, hi = int(a), int(b)
            if lo > hi:
                raise ValueError(f"{part}")
            ports.update(range(lo, hi + 1))
        else:
            ports.add(int(part))
    if not ports:
        raise ValueError("empty port list")
    if min(ports) < 1 or max(ports) > 65535:
        raise ValueError("ports must be between 1 and 65535")
    return sorted(ports)


# ---------------------------------------------------------------------------
# Host discovery
# ---------------------------------------------------------------------------

def _is_local(ip: str) -> bool:
    addr = ipaddress.ip_address(ip)
    return addr.is_private and not addr.is_loopback


def arp_scan(ips: list, timeout: int = 2):
    """ARP discovery through scapy. Returns {ip: mac}, or None on failure."""
    if not HAVE_SCAPY:
        return None
    try:
        answered, _ = srp(
            Ether(dst="ff:ff:ff:ff:ff:ff") / ARP(pdst=ips),
            timeout=timeout, retry=1, verbose=0,
        )
    except PermissionError:
        log(t("arp_permission"))
        return None
    except Exception as exc:  # noqa: BLE001
        log(t("arp_failed", err=exc))
        return None
    return {rcv.psrc: rcv.hwsrc for _, rcv in answered}


def tcp_ping(ip: str, ports=DISCOVERY_PORTS, timeout: float = 0.6) -> bool:
    """A host is up if any port accepts the connection or answers with RST."""
    for port in ports:
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.settimeout(timeout)
                if s.connect_ex((ip, port)) in _ALIVE_ERRNOS:
                    return True
        except OSError:
            continue
    return False


def _ping_cmd(ip: str, wait: int = 1) -> list:
    if sys.platform.startswith("win"):
        return ["ping", "-n", "1", "-w", str(wait * 1000), ip]
    if sys.platform == "darwin":  # macOS: -W is in milliseconds
        return ["ping", "-c", "1", "-W", str(wait * 1000), ip]
    return ["ping", "-c", "1", "-W", str(wait), ip]


def icmp_ping(ip: str) -> bool:
    """Ping through the OS `ping` binary (no raw sockets / root needed)."""
    if not shutil.which("ping"):
        return False
    try:
        result = subprocess.run(
            _ping_cmd(ip), stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL, timeout=3,
        )
        return result.returncode == 0
    except (OSError, subprocess.SubprocessError):
        return False


def _pool_map(func, items, workers: int, cancel=None):
    """Run func(item) on a thread pool and yield (item, result) as each one finishes.

    When the optional `cancel` event is set, queued work is dropped and the
    generator stops, so a scan can be interrupted quickly (Ctrl+C or the UI's
    Stop button) instead of draining the whole queue.
    """
    items = list(items)
    if not items:
        return
    ex = ThreadPoolExecutor(max_workers=max(1, min(workers, len(items))))
    futures = {ex.submit(func, item): item for item in items}
    pending = set(futures)
    try:
        while pending:
            if cancel is not None and cancel.is_set():
                return
            done, pending = wait(pending, timeout=0.2, return_when=FIRST_COMPLETED)
            for fut in done:
                yield futures[fut], fut.result()
    finally:
        for fut in pending:
            fut.cancel()
        ex.shutdown(wait=False)


def discover_hosts(ips: list, workers: int = 100, probe_ports=DISCOVERY_PORTS,
                   use_arp: bool = True, on_host=None, on_progress=None,
                   cancel=None) -> dict:
    """ARP first (local networks); if it finds nothing, fall back to ICMP + TCP.

    Optional hooks: on_host(ip, info) for every live host as soon as it is
    known, on_progress(done, total) while sweeping, and a `cancel` event.
    """
    if use_arp and HAVE_SCAPY and ips and all(_is_local(ip) for ip in ips):
        log(t("arp_start", n=len(ips)))
        arp = arp_scan(ips)
        if arp:
            found = {ip: {"mac": mac, "method": "ARP"} for ip, mac in arp.items()}
            for ip, info in found.items():
                if on_host:
                    on_host(ip, info)
            if on_progress:
                on_progress(len(ips), len(ips))
            log(t("found", n=len(found)))
            return found

    log(t("probe_start", n=len(ips)))
    found = {}

    def probe(ip):
        return icmp_ping(ip) or tcp_ping(ip, probe_ports)

    done = 0
    for ip, alive in _pool_map(probe, ips, workers, cancel):
        done += 1
        if alive:
            found[ip] = {"mac": None, "method": "ICMP/TCP"}
            if on_host:
                on_host(ip, found[ip])
        if on_progress:
            on_progress(done, len(ips))
    log(t("found", n=len(found)))
    return found


# ---------------------------------------------------------------------------
# Port scanning and banner grabbing
# ---------------------------------------------------------------------------

def service_name(port: int) -> str:
    if port in COMMON_SERVICE_NAMES:
        return COMMON_SERVICE_NAMES[port]
    try:
        return socket.getservbyport(port, "tcp")
    except OSError:
        return "unknown"


def _clean_banner(data: bytes) -> str:
    """One printable line. For HTTP replies: status line plus Server header."""
    text = data.decode("utf-8", errors="ignore")
    lines = [
        "".join(ch for ch in line if ch.isprintable()).strip()
        for line in text.splitlines()
    ]
    lines = [ln for ln in lines if ln]
    if not lines:
        return ""
    if lines[0].upper().startswith("HTTP/"):
        server = next((ln for ln in lines[1:] if ln.lower().startswith("server:")), "")
        return (lines[0] + (" | " + server if server else ""))[:120]
    return lines[0][:100]


def _grab_banner(sock: socket.socket, ip: str, port: int) -> str:
    """Listen first (SSH/FTP/SMTP talk first). If the port stays silent, send a
    harmless HTTP HEAD - but only on HTTP ports and on ports with no known
    non-HTTP service (we don't poke Redis, MySQL, etc. with web requests)."""
    if port in TLS_PORTS:
        return ""
    try:
        sock.settimeout(0.5)
        try:
            data = sock.recv(256)
        except socket.timeout:
            data = b""
            if port in HTTP_PORTS or port not in COMMON_SERVICE_NAMES:
                sock.sendall(
                    f"HEAD / HTTP/1.0\r\nHost: {ip}\r\nUser-Agent: Nemla\r\n\r\n".encode()
                )
                sock.settimeout(1.0)
                data = sock.recv(512)
        return _clean_banner(data)
    except OSError:
        return ""


def scan_port(ip: str, port: int, timeout: float = 0.7, grab: bool = True):
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(timeout)
            if s.connect_ex((ip, port)) != 0:
                return None
            banner = _grab_banner(s, ip, port) if grab else ""
    except OSError:
        return None
    return {"port": port, "service": service_name(port), "banner": banner}


def scan_host_ports(ip: str, ports: list, workers: int = 150,
                    timeout: float = 0.7, grab: bool = True, on_port=None,
                    on_progress=None, cancel=None) -> list:
    """Scan `ports` on one host. Optional hooks: on_port(result) for every open
    port as it is found, on_progress(done, total), and a `cancel` event."""
    found = []
    done = 0
    for _, res in _pool_map(lambda p: scan_port(ip, p, timeout, grab),
                            ports, workers, cancel):
        done += 1
        if res:
            found.append(res)
            if on_port:
                on_port(res)
        if on_progress:
            on_progress(done, len(ports))
    return sorted(found, key=lambda r: r["port"])


# ---------------------------------------------------------------------------
# OS fingerprinting (heuristic)
# ---------------------------------------------------------------------------

def get_ttl(ip: str):
    if HAVE_SCAPY:
        try:
            pkt = sr1(IP(dst=ip) / ICMP(), timeout=1, verbose=0)
            if pkt is not None:
                return int(pkt.ttl)
        except Exception:  # noqa: BLE001
            pass
    if shutil.which("ping"):
        try:
            out = subprocess.run(
                _ping_cmd(ip), capture_output=True, text=True, timeout=3
            ).stdout
            m = re.search(r"ttl[=:\s]*(\d+)", out, re.IGNORECASE)
            if m:
                return int(m.group(1))
        except (OSError, subprocess.SubprocessError):
            pass
    return None


def guess_os(ttl, open_ports: list) -> str:
    ports = {p["port"] for p in open_ports}
    if 3389 in ports or (445 in ports and 135 in ports):
        return t("os_rdp_smb")
    if ttl is None:
        return t("os_unknown")
    if ttl <= 64:
        base = "Linux / Unix / macOS"
        return t("os_ssh") if 22 in ports else base
    if ttl <= 128:
        return "Windows"
    return "Network device (Cisco/Solaris)"


# ---------------------------------------------------------------------------
# The scan pipeline (shared by the command line and the 3D interface)
# ---------------------------------------------------------------------------

def run_scan(target: str, ips: list, ports: list, *, no_ping: bool = False,
             no_os: bool = False, no_banner: bool = False, threads: int = 150,
             timeout: float = 0.7, emit=None, cancel=None):
    """Discover hosts, scan their ports, guess the OS. Returns (hosts, meta).

    `emit(event: dict)` receives live progress events (phase, progress, host,
    host_start, port, host_done) and `cancel` is a threading.Event that stops
    the scan early. `meta["discovered"]` is the number of live hosts found.
    """
    def send(event):
        if emit is not None:
            emit(event)

    cancel = cancel if cancel is not None else threading.Event()
    threads = max(1, threads)
    start = time.time()

    send({"type": "phase", "phase": "discovery", "total": len(ips)})
    if no_ping:
        log(t("skip_discovery", n=len(ips)))
        hosts_map = {ip: {"mac": None, "method": "skipped"} for ip in ips}
        for ip, info in hosts_map.items():
            send({"type": "host", "ip": ip, "mac": None, "method": info["method"]})
    else:
        probe_ports = sorted(set(DISCOVERY_PORTS) | set(ports[:15]))
        last = [0.0]

        def on_progress(done, total):
            now = time.time()
            if done >= total or now - last[0] >= 0.1:  # keep the event stream light
                last[0] = now
                send({"type": "progress", "phase": "discovery", "done": done, "total": total})

        hosts_map = discover_hosts(
            ips, workers=threads, probe_ports=probe_ports, cancel=cancel,
            on_progress=on_progress,
            on_host=lambda ip, info: send({"type": "host", "ip": ip,
                                           "mac": info.get("mac"),
                                           "method": info.get("method")}),
        )

    hosts = []
    if not hosts_map:
        log(t("no_hosts"))
    elif not cancel.is_set():
        log(t("port_count", n=len(ports)))
        order = sorted(hosts_map, key=lambda x: int(ipaddress.ip_address(x)))
        send({"type": "phase", "phase": "ports", "total": len(order), "ports": len(ports)})
        try:
            for index, ip in enumerate(order, 1):
                if cancel.is_set():
                    break
                log(t("scanning", ip=ip))
                send({"type": "host_start", "ip": ip, "index": index, "total": len(order)})
                port_last = [0.0]

                def on_port_progress(done, total, ip=ip, port_last=port_last):
                    now = time.time()
                    if done >= total or now - port_last[0] >= 0.1:
                        port_last[0] = now
                        send({"type": "progress", "phase": "ports", "ip": ip,
                              "done": done, "total": total})

                open_ports = scan_host_ports(
                    ip, ports, threads, timeout, grab=not no_banner, cancel=cancel,
                    on_progress=on_port_progress,
                    on_port=lambda res, ip=ip: send({"type": "port", "ip": ip, **res}),
                )
                if cancel.is_set():
                    break
                ttl = None
                if no_os:
                    os_guess = t("os_skipped")
                else:
                    ttl = get_ttl(ip)
                    os_guess = guess_os(ttl, open_ports)
                    if ttl:
                        os_guess += f" (TTL={ttl})"
                host = {
                    "ip": ip, "mac": hosts_map[ip].get("mac"),
                    "discovery": hosts_map[ip].get("method"),
                    "os_guess": os_guess, "ttl": ttl, "open_ports": open_ports,
                }
                hosts.append(host)
                send({"type": "host_done", "host": host})
                log(t("host_done", n=len(open_ports), os=os_guess))
        except KeyboardInterrupt:
            log(t("interrupted"))

    meta = {
        "target": target,
        "scan_time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "duration": time.time() - start,
        "ports_scanned": len(ports),
        "discovered": len(hosts_map),
        "cancelled": cancel.is_set(),
    }
    return hosts, meta


# ---------------------------------------------------------------------------
# Reports
# ---------------------------------------------------------------------------

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="@@LANG@@" dir="@@DIR@@">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>@@TITLE@@ - @@TARGET@@</title>
<style>
:root {
  --bg: #0a0c11; --panel: #10141c; --ant-orange: #ff7a1a;
  --ant-orange-dim: #b84400; --text: #eef0f6; --text-dim: #a2abbe;
  --border: #232a3b; --up: #3ee6b4;
}
* { box-sizing: border-box; }
body { background: var(--bg); color: var(--text); margin: 0; padding: 0 0 60px;
  font-family: 'Segoe UI', Tahoma, Arial, sans-serif; }
header { background: radial-gradient(600px 220px at 0% 0%, rgba(255,122,26,.16), transparent 70%), linear-gradient(135deg, #141924, #0a0c11);
  border-bottom: 2px solid var(--ant-orange); padding: 28px 32px;
  display: flex; align-items: center; }
header .icon { width: 56px; height: 56px; margin: 0 16px; flex: none; }
header .icon svg, footer svg { width: 100%; height: 100%; display: block; }
footer svg { display: inline-block; width: 16px; height: 16px; vertical-align: -3px; }
header h1 { margin: 0; color: var(--ant-orange); font-size: 26px; }
header p { margin: 4px 0 0; color: var(--text-dim); font-size: 13px; }
.summary { display: flex; flex-wrap: wrap; padding: 16px 24px 0; }
.stat { background: var(--panel); border: 1px solid var(--border);
  border-radius: 10px; padding: 14px 20px; min-width: 140px; margin: 8px; }
.stat .num { font-size: 26px; font-weight: 700; color: var(--ant-orange); }
.stat .label { font-size: 12px; color: var(--text-dim); margin-top: 2px; }
.container { padding: 24px 32px; }
.host-card { background: var(--panel); border: 1px solid var(--border);
  border-radius: 12px; margin-bottom: 18px; overflow: hidden; }
.host-header { display: flex; justify-content: space-between; align-items: center;
  padding: 14px 20px; background: #141924; border-bottom: 1px solid var(--border);
  flex-wrap: wrap; }
.host-ip { font-size: 17px; font-weight: 700; direction: ltr; unicode-bidi: isolate; }
.badge { display: inline-block; padding: 3px 10px; border-radius: 20px;
  font-size: 11px; font-weight: 600; margin: 0 4px 0 8px; }
.badge.up { background: rgba(111,207,111,.15); color: var(--up); border: 1px solid var(--up); }
.badge.os { background: rgba(255,140,0,.12); color: var(--ant-orange);
  border: 1px solid var(--ant-orange-dim); }
.host-meta { font-size: 12px; color: var(--text-dim); }
.table-wrap { overflow-x: auto; }
table { width: 100%; border-collapse: collapse; }
th, td { text-align: start; padding: 10px 20px; font-size: 13px; }
th { color: var(--text-dim); font-weight: 600; border-bottom: 1px solid var(--border); }
td { border-bottom: 1px solid var(--border); }
tr:last-child td { border-bottom: none; }
.port { color: var(--ant-orange); font-weight: 700; font-family: monospace; }
.banner { color: var(--text-dim); font-family: monospace; font-size: 11px;
  word-break: break-all; direction: ltr; unicode-bidi: isolate; text-align: left; }
.empty { padding: 16px 20px; color: var(--text-dim); font-size: 13px; }
footer { text-align: center; color: var(--text-dim); font-size: 12px; padding: 30px; }
</style>
</head>
<body>
<header>
  <div class="icon">@@MARK@@</div>
  <div>
    <h1>@@TITLE@@</h1>
    <p>@@L_TARGET@@: <bdi>@@TARGET@@</bdi> &nbsp;|&nbsp; @@L_DATE@@: <bdi>@@SCAN_TIME@@</bdi> &nbsp;|&nbsp; @@L_DURATION@@: <bdi>@@DURATION@@s</bdi></p>
  </div>
</header>
<div class="summary">
  <div class="stat"><div class="num">@@HOST_COUNT@@</div><div class="label">@@L_HOSTS@@</div></div>
  <div class="stat"><div class="num">@@OPEN_COUNT@@</div><div class="label">@@L_OPEN@@</div></div>
  <div class="stat"><div class="num">@@PORTS_SCANNED@@</div><div class="label">@@L_SCANNED@@</div></div>
</div>
<div class="container">
@@HOST_CARDS@@
</div>
<footer>@@MARK_SMALL@@ @@FOOTER@@</footer>
</body>
</html>
"""

# The Nemla mark (see nemla_ui/web/brand/nemla-mark.svg), inlined so reports stay one file.
BRAND_MARK = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 256" role="img" aria-label="Nemla">'
    '<defs><linearGradient id="nm-ember@@ID@@" x1="60" y1="20" x2="200" y2="228" gradientUnits="userSpaceOnUse">'
    '<stop offset="0" stop-color="#FFC46B"/><stop offset=".5" stop-color="#FF7A1A"/>'
    '<stop offset="1" stop-color="#E8460C"/></linearGradient></defs>'
    '<g fill="url(#nm-ember@@ID@@)"><ellipse cx="128" cy="62" rx="19" ry="17"/>'
    '<ellipse cx="128" cy="109" rx="16" ry="23"/>'
    '<path d="M128 138c22 0 34 20 34 40 0 24-14 42-34 46-20-4-34-22-34-46 0-20 12-40 34-40z"/>'
    '<circle cx="58" cy="104" r="7"/><circle cx="48" cy="144" r="7"/><circle cx="64" cy="190" r="7"/>'
    '<circle cx="198" cy="104" r="7"/><circle cx="208" cy="144" r="7"/><circle cx="192" cy="190" r="7"/>'
    '<circle cx="82" cy="24" r="6"/><circle cx="174" cy="24" r="6"/></g>'
    '<g fill="none" stroke="url(#nm-ember@@ID@@)" stroke-width="7" stroke-linecap="round" stroke-linejoin="round">'
    '<path d="M114 98 80 80 58 104M112 110 72 114 48 144M114 124 80 148 64 190"/>'
    '<path d="M142 98 176 80 198 104M144 110 184 114 208 144M142 124 176 148 192 190"/>'
    '<path d="M119 50 102 28 82 24M137 50 154 28 174 24" stroke-width="5.5"/></g></svg>'
)


def _e(value) -> str:
    """HTML-escape anything that ends up in the report (banners are attacker-controlled)."""
    return html.escape("" if value is None else str(value), quote=True)


def render_host_card(host: dict) -> str:
    if host["open_ports"]:
        rows = "\n".join(
            f'<tr><td class="port">{_e(p["port"])}</td>'
            f'<td>{_e(p["service"])}</td>'
            f'<td class="banner">{_e(p["banner"] or "-")}</td></tr>'
            for p in host["open_ports"]
        )
        body = (
            '<div class="table-wrap"><table>'
            f'<tr><th>{_e(t("r_port"))}</th><th>{_e(t("r_service"))}</th>'
            f'<th>{_e(t("r_banner"))}</th></tr>{rows}</table></div>'
        )
    else:
        body = f'<div class="empty">{_e(t("r_no_ports"))}</div>'
    mac = f"MAC: {_e(host['mac'])}" if host.get("mac") else ""
    return (
        '<div class="host-card"><div class="host-header"><div>'
        f'<span class="host-ip">{_e(host["ip"])}</span>'
        f'<span class="badge up">{_e(t("r_active"))}</span>'
        f'<span class="badge os">{_e(host["os_guess"])}</span>'
        f'</div><div class="host-meta">{mac}</div></div>{body}</div>'
    )


def render_html(meta: dict, hosts: list) -> str:
    cards = "\n".join(render_host_card(h) for h in hosts) or (
        f'<p class="empty">{_e(t("r_no_hosts"))}</p>'
    )
    values = {
        "LANG": _LANG,
        "DIR": "rtl" if _LANG == "ar" else "ltr",
        "TITLE": _e(t("r_title")),
        "TARGET": _e(meta["target"]),
        "SCAN_TIME": _e(meta["scan_time"]),
        "DURATION": _e(f"{meta['duration']:.1f}"),
        "HOST_COUNT": str(len(hosts)),
        "OPEN_COUNT": str(sum(len(h["open_ports"]) for h in hosts)),
        "PORTS_SCANNED": str(meta["ports_scanned"]),
        "L_TARGET": _e(t("r_target")),
        "L_DATE": _e(t("r_date")),
        "L_DURATION": _e(t("r_duration")),
        "L_HOSTS": _e(t("r_hosts")),
        "L_OPEN": _e(t("r_open")),
        "L_SCANNED": _e(t("r_scanned")),
        "FOOTER": _e(t("r_footer", ver=__version__)),
        "HOST_CARDS": cards,  # already escaped piece by piece
        "MARK": BRAND_MARK.replace("@@ID@@", "a"),  # fixed markup, no scan data
        "MARK_SMALL": BRAND_MARK.replace("@@ID@@", "b"),
    }
    # one pass, so text that came from a scanned host can never be treated as a placeholder
    return re.sub(r"@@([A-Z_]+)@@", lambda m: values.get(m.group(1), m.group(0)), HTML_TEMPLATE)


def json_text(meta: dict, hosts: list) -> str:
    payload = {
        "tool": "nemla", "version": __version__, "target": meta["target"],
        "scan_time": meta["scan_time"],
        "duration_seconds": round(meta["duration"], 2),
        "ports_scanned_per_host": meta["ports_scanned"], "hosts": hosts,
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


def csv_text(hosts: list) -> str:
    buf = io.StringIO(newline="")
    w = csv.writer(buf)
    w.writerow(["ip", "mac", "os_guess", "ttl", "port", "service", "banner"])
    for h in hosts:
        base = [h["ip"], h.get("mac") or "", h["os_guess"], h.get("ttl") or ""]
        if not h["open_ports"]:
            w.writerow(base + ["", "", ""])
        for p in h["open_ports"]:
            w.writerow(base + [p["port"], p["service"], p["banner"]])
    return buf.getvalue()


def write_json(path: str, meta: dict, hosts: list) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(json_text(meta, hosts))


def write_csv(path: str, hosts: list) -> None:
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(csv_text(hosts))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="nemla",
        description="Nemla (نملة) - lightweight network reconnaissance tool. "
                    "Run it without arguments to open the 3D interface.",
        epilog="Only scan systems you own or have explicit permission to test.",
    )
    p.add_argument("-t", "--target",
                   help="IP, hostname, CIDR (10.0.0.0/24), range (10.0.0.1-50 or 10.0.0.1-10.0.0.50)")
    p.add_argument("-p", "--ports", help="ports: 22 | 22,80,443 | 1-1000")
    p.add_argument("--top-ports", action="store_true",
                   help="scan the common-ports list (default when -p is not given)")
    p.add_argument("-o", "--output", default="nemla_report.html", help="HTML report path")
    p.add_argument("--json", metavar="FILE", help="also write results as JSON")
    p.add_argument("--csv", metavar="FILE", help="also write results as CSV")
    p.add_argument("--no-os", action="store_true", help="skip OS fingerprinting")
    p.add_argument("--no-ping", action="store_true",
                   help="skip host discovery, treat every target as up (like nmap -Pn)")
    p.add_argument("--no-banner", action="store_true", help="skip banner grabbing")
    p.add_argument("--threads", type=int, default=150, help="worker threads (default 150)")
    p.add_argument("--timeout", type=float, default=0.7,
                   help="TCP connect timeout in seconds (default 0.7)")
    p.add_argument("--max-hosts", type=int, default=1024,
                   help="refuse targets larger than this many addresses (default 1024)")
    p.add_argument("--lang", choices=sorted(STRINGS),
                   help="interface and report language (default en)")
    p.add_argument("--version", action="version", version=f"nemla {__version__}")

    ui = p.add_argument_group("3D interface")
    ui.add_argument("--ui", action="store_true",
                    help="open the 3D interface (this is also what happens with no arguments)")
    ui.add_argument("--ui-port", type=int, default=0, metavar="PORT",
                    help="port for the local interface server (default: any free port)")
    ui.add_argument("--no-browser", action="store_true",
                    help="start the interface server but do not open a window")
    ui.add_argument("--keep-alive", action="store_true",
                    help="keep the server running after its window is closed")
    ui.add_argument("--install-launcher", action="store_true",
                    help="Linux: add Nemla to your applications menu (installs under ~/.local)")
    ui.add_argument("--uninstall-launcher", action="store_true",
                    help="Linux: remove the applications-menu entry again")
    return p


def launch_ui(args) -> int:
    """Start the local 3D interface (needs the nemla_ui/ folder next to this file)."""
    try:
        from nemla_ui import serve
    except ImportError:
        log("The 3D interface files (the nemla_ui/ folder) were not found next to nemla.py.")
        return 1
    return serve(sys.modules[__name__], port=args.ui_port, open_window=not args.no_browser,
                 keep_alive=args.keep_alive, lang=args.lang)


def manage_launcher(args) -> int:
    try:
        from nemla_ui import launcher
    except ImportError:
        log("The 3D interface files (the nemla_ui/ folder) were not found next to nemla.py.")
        return 1
    if args.install_launcher:
        return launcher.install()
    return launcher.uninstall()


def main(argv=None) -> int:
    global _LANG
    parser = build_parser()
    bare = not (sys.argv[1:] if argv is None else list(argv))
    args = parser.parse_args(argv)
    _LANG = args.lang or "en"
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass

    if args.install_launcher or args.uninstall_launcher:
        return manage_launcher(args)
    if args.ui or bare:
        print_banner()
        return launch_ui(args)
    if not args.target:
        parser.error("the following arguments are required: -t/--target "
                     "(or run nemla with no arguments to open the 3D interface)")
    print_banner()

    try:
        ips = parse_targets(args.target, args.max_hosts)
    except ValueError as err:
        log(t("invalid_target", err=err))
        return 1

    try:
        ports = set(parse_ports(args.ports)) if args.ports else set()
    except ValueError as err:
        log(t("invalid_ports", err=err))
        return 1
    if args.top_ports or not ports:
        ports |= set(TOP_PORTS)
    ports = sorted(ports)

    hosts, meta = run_scan(
        args.target, ips, ports, no_ping=args.no_ping, no_os=args.no_os,
        no_banner=args.no_banner, threads=args.threads, timeout=args.timeout,
    )
    if not meta["discovered"]:
        return 0
    log(t("done", sec=meta["duration"]))

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(render_html(meta, hosts))
    log(t("saved", kind="HTML", path=args.output))
    if args.json:
        write_json(args.json, meta, hosts)
        log(t("saved", kind="JSON", path=args.json))
    if args.csv:
        write_csv(args.csv, hosts)
        log(t("saved", kind="CSV", path=args.csv))
    return 0


if __name__ == "__main__":
    sys.exit(main())
