#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Nemla (نملة) - lightweight network reconnaissance tool.

Discover hosts, scan TCP ports, grab banners, guess the OS and generate
an HTML / JSON / CSV report.

Examples:
    sudo python3 nemla.py -t 192.168.1.0/24
    python3 nemla.py -t 192.168.1.1-50 -p 1-1000
    python3 nemla.py -t 192.168.1.10 --top-ports --lang ar
    python3 nemla.py -t scanme.example.org -p 22,80,443 --json out.json

Only scan systems and networks you own or have explicit permission to test.
"""
from __future__ import annotations

import argparse
import csv
import errno
import html
import ipaddress
import json
import re
import shutil
import socket
import subprocess
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime

try:  # scapy is optional: it enables ARP discovery and raw-ICMP TTL probing
    from scapy.all import ARP, Ether, ICMP, IP, conf as scapy_conf, sr1, srp

    scapy_conf.verb = 0
    HAVE_SCAPY = True
except Exception:  # pragma: no cover - depends on the environment
    HAVE_SCAPY = False

__version__ = "1.1.0"

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TOP_PORTS = sorted({
    21, 22, 23, 25, 53, 80, 110, 111, 135, 139, 143, 443, 445, 465, 587,
    993, 995, 1080, 1433, 1521, 1723, 2049, 3128, 3306, 3389, 5432, 5900,
    5985, 6000, 6379, 8000, 8080, 8081, 8443, 8888, 9200, 11211, 27017,
})

COMMON_SERVICE_NAMES = {
    21: "FTP", 22: "SSH", 23: "Telnet", 25: "SMTP", 53: "DNS", 80: "HTTP",
    110: "POP3", 111: "RPCBind", 135: "MS-RPC", 139: "NetBIOS", 143: "IMAP",
    443: "HTTPS", 445: "SMB", 465: "SMTPS", 587: "SMTP-Submission",
    993: "IMAPS", 995: "POP3S", 1080: "SOCKS", 1433: "MSSQL", 1521: "Oracle",
    1723: "PPTP", 2049: "NFS", 3128: "Squid", 3306: "MySQL", 3389: "RDP",
    5432: "PostgreSQL", 5900: "VNC", 5985: "WinRM", 6000: "X11",
    6379: "Redis", 8000: "HTTP-Alt", 8080: "HTTP-Proxy", 8081: "HTTP-Alt",
    8443: "HTTPS-Alt", 8888: "HTTP-Alt", 9200: "Elasticsearch",
    11211: "Memcached", 27017: "MongoDB",
}

HTTP_PORTS = {80, 3128, 8000, 8080, 8081, 8888}
TLS_PORTS = {443, 465, 636, 993, 995, 8443}
DISCOVERY_PORTS = (80, 443, 22, 445, 3389, 135, 8080)

# connect_ex results that prove a host is alive (open port, or a RST reply)
_ALIVE_ERRNOS = {0, errno.ECONNREFUSED, 10061}

# ---------------------------------------------------------------------------
# Translations
# ---------------------------------------------------------------------------

STRINGS = {
    "en": {
        "notice": "Use only on networks you own or are authorized to test.",
        "arp_start": "Discovering hosts via ARP ({n} addresses)...",
        "probe_start": "Discovering hosts via ICMP + TCP ({n} addresses)...",
        "arp_permission": "ARP scan needs elevated privileges (try sudo). Falling back to ICMP/TCP.",
        "arp_failed": "ARP scan failed ({err}). Falling back to ICMP/TCP.",
        "found": "Discovered {n} host(s)",
        "no_hosts": "No hosts discovered. Check connectivity, or use --no-ping if the target blocks ping.",
        "skip_discovery": "Discovery skipped, treating all {n} target(s) as up.",
        "port_count": "Scanning {n} port(s) per host",
        "scanning": "Scanning {ip} ...",
        "host_done": "-> {n} open port(s) | OS: {os}",
        "done": "Scan finished in {sec:.1f}s",
        "interrupted": "Interrupted - saving partial results.",
        "saved": "{kind} saved: {path}",
        "invalid_target": "Invalid target: {err}",
        "invalid_ports": "Invalid ports: {err}",
        "too_many": "Target has {n} addresses, above the --max-hosts limit ({limit}). Raise --max-hosts if you really mean it.",
        "ipv6": "IPv6 targets are not supported yet.",
        "bad_range": "Bad IP range: {spec}",
        "cannot_resolve": "cannot resolve '{spec}'",
        "os_unknown": "Unknown",
        "os_skipped": "Skipped",
        "os_rdp_smb": "Windows (RDP/SMB detected)",
        "os_ssh": "Linux / Unix (SSH detected)",
        "r_title": "Nemla Recon Report",
        "r_target": "Target",
        "r_date": "Scan date",
        "r_duration": "Duration",
        "r_hosts": "Hosts discovered",
        "r_open": "Open ports",
        "r_scanned": "Ports scanned per host",
        "r_port": "Port",
        "r_service": "Service",
        "r_banner": "Banner",
        "r_no_ports": "No open ports in the scanned range",
        "r_no_hosts": "No hosts to display",
        "r_active": "Active",
        "r_footer": "Generated by Nemla v{ver} - responsible use only, on networks you are authorized to scan",
        "desc": "Nemla - lightweight network reconnaissance tool",
    },
    "ar": {
        "notice": "استخدمها فقط على شبكات تملكها أو لديك تصريح صريح لفحصها.",
        "arp_start": "اكتشاف الأجهزة عبر ARP ({n} عنوان)...",
        "probe_start": "اكتشاف الأجهزة عبر ICMP + TCP ({n} عنوان)...",
        "arp_permission": "فحص ARP يحتاج صلاحيات أعلى (جرّب sudo). سيتم التحويل إلى ICMP/TCP.",
        "arp_failed": "فشل فحص ARP ({err}). سيتم التحويل إلى ICMP/TCP.",
        "found": "تم اكتشاف {n} جهاز",
        "no_hosts": "لم يتم اكتشاف أي جهاز. تأكد من الاتصال، أو استخدم --no-ping إذا كان الهدف يحجب ping.",
        "skip_discovery": "تم تخطي الاكتشاف، سيتم اعتبار الأهداف ({n}) كلها شغّالة.",
        "port_count": "فحص {n} منفذ لكل جهاز",
        "scanning": "فحص {ip} ...",
        "host_done": "-> {n} منفذ مفتوح | نظام التشغيل: {os}",
        "done": "اكتمل الفحص خلال {sec:.1f} ثانية",
        "interrupted": "تم الإيقاف - سيتم حفظ النتائج الجزئية.",
        "saved": "تم حفظ {kind}: {path}",
        "invalid_target": "هدف غير صالح: {err}",
        "invalid_ports": "منافذ غير صالحة: {err}",
        "too_many": "الهدف فيه {n} عنوان، وهذا أكبر من حد --max-hosts ({limit}). ارفع الحد إذا كنت متأكداً.",
        "ipv6": "عناوين IPv6 غير مدعومة حالياً.",
        "bad_range": "نطاق IP غير صالح: {spec}",
        "cannot_resolve": "تعذّر حل الاسم '{spec}'",
        "os_unknown": "غير معروف",
        "os_skipped": "تم التخطي",
        "os_rdp_smb": "Windows (تم اكتشاف RDP/SMB)",
        "os_ssh": "Linux / Unix (تم اكتشاف SSH)",
        "r_title": "تقرير نملة",
        "r_target": "الهدف",
        "r_date": "تاريخ الفحص",
        "r_duration": "المدة",
        "r_hosts": "أجهزة مكتشفة",
        "r_open": "منافذ مفتوحة",
        "r_scanned": "منفذ تم فحصه لكل جهاز",
        "r_port": "المنفذ",
        "r_service": "الخدمة",
        "r_banner": "Banner",
        "r_no_ports": "لا توجد منافذ مفتوحة ضمن النطاق المفحوص",
        "r_no_hosts": "لا توجد أجهزة لعرضها",
        "r_active": "شغّال",
        "r_footer": "تم توليده بواسطة نملة (Nemla) v{ver} - استخدام مسؤول فقط على شبكات مصرّح بفحصها",
        "desc": "نملة - أداة استطلاع شبكة خفيفة",
    },
}

_LANG = "en"
_PRINT_LOCK = threading.Lock()


def t(key: str, **kw) -> str:
    """Translate `key` into the active language (falls back to English)."""
    text = STRINGS.get(_LANG, {}).get(key) or STRINGS["en"][key]
    return text.format(**kw) if kw else text


def log(msg: str) -> None:
    with _PRINT_LOCK:
        print(f"[{datetime.now():%H:%M:%S}] {msg}", flush=True)


def print_banner() -> None:
    print(f"\n  \U0001F41C  Nemla / نملة  v{__version__}  -  Network Recon")
    print(f"  {t('notice')}\n")


# ---------------------------------------------------------------------------
# Target and port parsing
# ---------------------------------------------------------------------------

def parse_targets(spec: str, max_hosts: int = 1024) -> list:
    """Turn a target spec into a list of IPv4 address strings.

    Supported: single IP, hostname, CIDR (10.0.0.0/24), full range
    (10.0.0.1-10.0.0.50) and short range (10.0.0.1-50).
    """
    spec = spec.strip()
    if not spec:
        raise ValueError(t("bad_range", spec=spec))

    if "/" in spec:
        net = ipaddress.ip_network(spec, strict=False)
        if net.version != 4:
            raise ValueError(t("ipv6"))
        if net.num_addresses > max_hosts:
            raise ValueError(t("too_many", n=net.num_addresses, limit=max_hosts))
        hosts = list(net.hosts()) or list(net)
        return [str(h) for h in hosts]

    m = re.fullmatch(r"(\d+\.\d+\.\d+\.\d+)-(\d+(?:\.\d+\.\d+\.\d+)?)", spec)
    if m:
        first = ipaddress.ip_address(m.group(1))
        end = m.group(2)
        if "." not in end:  # short form: only the last octet changes
            prefix = m.group(1).rsplit(".", 1)[0]
            last = ipaddress.ip_address(f"{prefix}.{end}")
        else:
            last = ipaddress.ip_address(end)
        if last < first:
            raise ValueError(t("bad_range", spec=spec))
        count = int(last) - int(first) + 1
        if count > max_hosts:
            raise ValueError(t("too_many", n=count, limit=max_hosts))
        return [str(ipaddress.ip_address(int(first) + i)) for i in range(count)]

    try:
        addr = ipaddress.ip_address(spec)
    except ValueError:
        try:  # maybe a hostname
            return [socket.gethostbyname(spec)]
        except OSError:
            raise ValueError(t("cannot_resolve", spec=spec)) from None
    if addr.version != 4:
        raise ValueError(t("ipv6"))
    return [str(addr)]


def parse_ports(spec: str) -> list:
    """Parse '22', '22,80,443' or '1-1000' (and mixes) into sorted ports."""
    ports = set()
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            a, b = part.split("-", 1)
            lo, hi = int(a), int(b)
            if lo > hi:
                raise ValueError(f"{part}")
            ports.update(range(lo, hi + 1))
        else:
            ports.add(int(part))
    if not ports:
        raise ValueError("empty port list")
    if min(ports) < 1 or max(ports) > 65535:
        raise ValueError("ports must be between 1 and 65535")
    return sorted(ports)


# ---------------------------------------------------------------------------
# Host discovery
# ---------------------------------------------------------------------------

def _is_local(ip: str) -> bool:
    addr = ipaddress.ip_address(ip)
    return addr.is_private and not addr.is_loopback


def arp_scan(ips: list, timeout: int = 2):
    """ARP discovery through scapy. Returns {ip: mac}, or None on failure."""
    if not HAVE_SCAPY:
        return None
    try:
        answered, _ = srp(
            Ether(dst="ff:ff:ff:ff:ff:ff") / ARP(pdst=ips),
            timeout=timeout, retry=1, verbose=0,
        )
    except PermissionError:
        log(t("arp_permission"))
        return None
    except Exception as exc:  # noqa: BLE001
        log(t("arp_failed", err=exc))
        return None
    return {rcv.psrc: rcv.hwsrc for _, rcv in answered}


def tcp_ping(ip: str, ports=DISCOVERY_PORTS, timeout: float = 0.6) -> bool:
    """A host is up if any port accepts the connection or answers with RST."""
    for port in ports:
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
                s.settimeout(timeout)
                if s.connect_ex((ip, port)) in _ALIVE_ERRNOS:
                    return True
        except OSError:
            continue
    return False


def _ping_cmd(ip: str, wait: int = 1) -> list:
    if sys.platform.startswith("win"):
        return ["ping", "-n", "1", "-w", str(wait * 1000), ip]
    if sys.platform == "darwin":  # macOS: -W is in milliseconds
        return ["ping", "-c", "1", "-W", str(wait * 1000), ip]
    return ["ping", "-c", "1", "-W", str(wait), ip]


def icmp_ping(ip: str) -> bool:
    """Ping through the OS `ping` binary (no raw sockets / root needed)."""
    if not shutil.which("ping"):
        return False
    try:
        result = subprocess.run(
            _ping_cmd(ip), stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL, timeout=3,
        )
        return result.returncode == 0
    except (OSError, subprocess.SubprocessError):
        return False


def discover_hosts(ips: list, workers: int = 100, probe_ports=DISCOVERY_PORTS,
                   use_arp: bool = True) -> dict:
    """ARP first (local networks); if it finds nothing, fall back to ICMP + TCP."""
    if use_arp and HAVE_SCAPY and ips and all(_is_local(ip) for ip in ips):
        log(t("arp_start", n=len(ips)))
        arp = arp_scan(ips)
        if arp:
            found = {ip: {"mac": mac, "method": "ARP"} for ip, mac in arp.items()}
            log(t("found", n=len(found)))
            return found

    log(t("probe_start", n=len(ips)))
    found = {}

    def probe(ip):
        return ip if (icmp_ping(ip) or tcp_ping(ip, probe_ports)) else None

    with ThreadPoolExecutor(max_workers=max(1, min(workers, len(ips)))) as ex:
        for fut in as_completed([ex.submit(probe, ip) for ip in ips]):
            ip = fut.result()
            if ip:
                found[ip] = {"mac": None, "method": "ICMP/TCP"}
    log(t("found", n=len(found)))
    return found


# ---------------------------------------------------------------------------
# Port scanning and banner grabbing
# ---------------------------------------------------------------------------

def service_name(port: int) -> str:
    if port in COMMON_SERVICE_NAMES:
        return COMMON_SERVICE_NAMES[port]
    try:
        return socket.getservbyport(port, "tcp")
    except OSError:
        return "unknown"


def _clean_banner(data: bytes) -> str:
    """One printable line. For HTTP replies: status line plus Server header."""
    text = data.decode("utf-8", errors="ignore")
    lines = [
        "".join(ch for ch in line if ch.isprintable()).strip()
        for line in text.splitlines()
    ]
    lines = [ln for ln in lines if ln]
    if not lines:
        return ""
    if lines[0].upper().startswith("HTTP/"):
        server = next((ln for ln in lines[1:] if ln.lower().startswith("server:")), "")
        return (lines[0] + (" | " + server if server else ""))[:120]
    return lines[0][:100]


def _grab_banner(sock: socket.socket, ip: str, port: int) -> str:
    """Listen first (SSH/FTP/SMTP talk first). If the port stays silent, send a
    harmless HTTP HEAD - but only on HTTP ports and on ports with no known
    non-HTTP service (we don't poke Redis, MySQL, etc. with web requests)."""
    if port in TLS_PORTS:
        return ""
    try:
        sock.settimeout(0.5)
        try:
            data = sock.recv(256)
        except socket.timeout:
            data = b""
            if port in HTTP_PORTS or port not in COMMON_SERVICE_NAMES:
                sock.sendall(
                    f"HEAD / HTTP/1.0\r\nHost: {ip}\r\nUser-Agent: Nemla\r\n\r\n".encode()
                )
                sock.settimeout(1.0)
                data = sock.recv(512)
        return _clean_banner(data)
    except OSError:
        return ""


def scan_port(ip: str, port: int, timeout: float = 0.7, grab: bool = True):
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(timeout)
            if s.connect_ex((ip, port)) != 0:
                return None
            banner = _grab_banner(s, ip, port) if grab else ""
    except OSError:
        return None
    return {"port": port, "service": service_name(port), "banner": banner}


def scan_host_ports(ip: str, ports: list, workers: int = 150,
                    timeout: float = 0.7, grab: bool = True) -> list:
    found = []
    with ThreadPoolExecutor(max_workers=max(1, min(workers, len(ports)))) as ex:
        futures = [ex.submit(scan_port, ip, p, timeout, grab) for p in ports]
        for fut in as_completed(futures):
            res = fut.result()
            if res:
                found.append(res)
    return sorted(found, key=lambda r: r["port"])


# ---------------------------------------------------------------------------
# OS fingerprinting (heuristic)
# ---------------------------------------------------------------------------

def get_ttl(ip: str):
    if HAVE_SCAPY:
        try:
            pkt = sr1(IP(dst=ip) / ICMP(), timeout=1, verbose=0)
            if pkt is not None:
                return int(pkt.ttl)
        except Exception:  # noqa: BLE001
            pass
    if shutil.which("ping"):
        try:
            out = subprocess.run(
                _ping_cmd(ip), capture_output=True, text=True, timeout=3
            ).stdout
            m = re.search(r"ttl[=:\s]*(\d+)", out, re.IGNORECASE)
            if m:
                return int(m.group(1))
        except (OSError, subprocess.SubprocessError):
            pass
    return None


def guess_os(ttl, open_ports: list) -> str:
    ports = {p["port"] for p in open_ports}
    if 3389 in ports or (445 in ports and 135 in ports):
        return t("os_rdp_smb")
    if ttl is None:
        return t("os_unknown")
    if ttl <= 64:
        base = "Linux / Unix / macOS"
        return t("os_ssh") if 22 in ports else base
    if ttl <= 128:
        return "Windows"
    return "Network device (Cisco/Solaris)"


# ---------------------------------------------------------------------------
# Reports
# ---------------------------------------------------------------------------

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="@@LANG@@" dir="@@DIR@@">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>@@TITLE@@ - @@TARGET@@</title>
<style>
:root {
  --bg: #0d0d0d; --panel: #171512; --ant-orange: #ff8c00;
  --ant-orange-dim: #b35f00; --text: #eee8dc; --text-dim: #9a9184;
  --border: #2a251f; --up: #6fcf6f;
}
* { box-sizing: border-box; }
body { background: var(--bg); color: var(--text); margin: 0; padding: 0 0 60px;
  font-family: 'Segoe UI', Tahoma, Arial, sans-serif; }
header { background: linear-gradient(135deg, #1a1611, #0d0d0d);
  border-bottom: 2px solid var(--ant-orange); padding: 28px 32px;
  display: flex; align-items: center; }
header .icon { font-size: 42px; margin: 0 16px; }
header h1 { margin: 0; color: var(--ant-orange); font-size: 26px; }
header p { margin: 4px 0 0; color: var(--text-dim); font-size: 13px; }
.summary { display: flex; flex-wrap: wrap; padding: 16px 24px 0; }
.stat { background: var(--panel); border: 1px solid var(--border);
  border-radius: 10px; padding: 14px 20px; min-width: 140px; margin: 8px; }
.stat .num { font-size: 26px; font-weight: 700; color: var(--ant-orange); }
.stat .label { font-size: 12px; color: var(--text-dim); margin-top: 2px; }
.container { padding: 24px 32px; }
.host-card { background: var(--panel); border: 1px solid var(--border);
  border-radius: 12px; margin-bottom: 18px; overflow: hidden; }
.host-header { display: flex; justify-content: space-between; align-items: center;
  padding: 14px 20px; background: #1c1812; border-bottom: 1px solid var(--border);
  flex-wrap: wrap; }
.host-ip { font-size: 17px; font-weight: 700; direction: ltr; unicode-bidi: isolate; }
.badge { display: inline-block; padding: 3px 10px; border-radius: 20px;
  font-size: 11px; font-weight: 600; margin: 0 4px 0 8px; }
.badge.up { background: rgba(111,207,111,.15); color: var(--up); border: 1px solid var(--up); }
.badge.os { background: rgba(255,140,0,.12); color: var(--ant-orange);
  border: 1px solid var(--ant-orange-dim); }
.host-meta { font-size: 12px; color: var(--text-dim); }
.table-wrap { overflow-x: auto; }
table { width: 100%; border-collapse: collapse; }
th, td { text-align: start; padding: 10px 20px; font-size: 13px; }
th { color: var(--text-dim); font-weight: 600; border-bottom: 1px solid var(--border); }
td { border-bottom: 1px solid var(--border); }
tr:last-child td { border-bottom: none; }
.port { color: var(--ant-orange); font-weight: 700; font-family: monospace; }
.banner { color: var(--text-dim); font-family: monospace; font-size: 11px;
  word-break: break-all; direction: ltr; unicode-bidi: isolate; text-align: left; }
.empty { padding: 16px 20px; color: var(--text-dim); font-size: 13px; }
footer { text-align: center; color: var(--text-dim); font-size: 12px; padding: 30px; }
</style>
</head>
<body>
<header>
  <div class="icon">&#128028;</div>
  <div>
    <h1>@@TITLE@@</h1>
    <p>@@L_TARGET@@: <bdi>@@TARGET@@</bdi> &nbsp;|&nbsp; @@L_DATE@@: <bdi>@@SCAN_TIME@@</bdi> &nbsp;|&nbsp; @@L_DURATION@@: <bdi>@@DURATION@@s</bdi></p>
  </div>
</header>
<div class="summary">
  <div class="stat"><div class="num">@@HOST_COUNT@@</div><div class="label">@@L_HOSTS@@</div></div>
  <div class="stat"><div class="num">@@OPEN_COUNT@@</div><div class="label">@@L_OPEN@@</div></div>
  <div class="stat"><div class="num">@@PORTS_SCANNED@@</div><div class="label">@@L_SCANNED@@</div></div>
</div>
<div class="container">
@@HOST_CARDS@@
</div>
<footer>&#128028; @@FOOTER@@</footer>
</body>
</html>
"""


def _e(value) -> str:
    """HTML-escape anything that ends up in the report (banners are attacker-controlled)."""
    return html.escape("" if value is None else str(value), quote=True)


def render_host_card(host: dict) -> str:
    if host["open_ports"]:
        rows = "\n".join(
            f'<tr><td class="port">{_e(p["port"])}</td>'
            f'<td>{_e(p["service"])}</td>'
            f'<td class="banner">{_e(p["banner"] or "-")}</td></tr>'
            for p in host["open_ports"]
        )
        body = (
            '<div class="table-wrap"><table>'
            f'<tr><th>{_e(t("r_port"))}</th><th>{_e(t("r_service"))}</th>'
            f'<th>{_e(t("r_banner"))}</th></tr>{rows}</table></div>'
        )
    else:
        body = f'<div class="empty">{_e(t("r_no_ports"))}</div>'
    mac = f"MAC: {_e(host['mac'])}" if host.get("mac") else ""
    return (
        '<div class="host-card"><div class="host-header"><div>'
        f'<span class="host-ip">{_e(host["ip"])}</span>'
        f'<span class="badge up">{_e(t("r_active"))}</span>'
        f'<span class="badge os">{_e(host["os_guess"])}</span>'
        f'</div><div class="host-meta">{mac}</div></div>{body}</div>'
    )


def render_html(meta: dict, hosts: list) -> str:
    cards = "\n".join(render_host_card(h) for h in hosts) or (
        f'<p class="empty">{_e(t("r_no_hosts"))}</p>'
    )
    values = {
        "LANG": _LANG,
        "DIR": "rtl" if _LANG == "ar" else "ltr",
        "TITLE": _e(t("r_title")),
        "TARGET": _e(meta["target"]),
        "SCAN_TIME": _e(meta["scan_time"]),
        "DURATION": _e(f"{meta['duration']:.1f}"),
        "HOST_COUNT": str(len(hosts)),
        "OPEN_COUNT": str(sum(len(h["open_ports"]) for h in hosts)),
        "PORTS_SCANNED": str(meta["ports_scanned"]),
        "L_TARGET": _e(t("r_target")),
        "L_DATE": _e(t("r_date")),
        "L_DURATION": _e(t("r_duration")),
        "L_HOSTS": _e(t("r_hosts")),
        "L_OPEN": _e(t("r_open")),
        "L_SCANNED": _e(t("r_scanned")),
        "FOOTER": _e(t("r_footer", ver=__version__)),
        "HOST_CARDS": cards,  # already escaped piece by piece
    }
    out = HTML_TEMPLATE
    for key, val in values.items():
        out = out.replace(f"@@{key}@@", val)
    return out


def write_json(path: str, meta: dict, hosts: list) -> None:
    payload = {
        "tool": "nemla", "version": __version__, "target": meta["target"],
        "scan_time": meta["scan_time"],
        "duration_seconds": round(meta["duration"], 2),
        "ports_scanned_per_host": meta["ports_scanned"], "hosts": hosts,
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)


def write_csv(path: str, hosts: list) -> None:
    with open(path, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["ip", "mac", "os_guess", "ttl", "port", "service", "banner"])
        for h in hosts:
            base = [h["ip"], h.get("mac") or "", h["os_guess"], h.get("ttl") or ""]
            if not h["open_ports"]:
                w.writerow(base + ["", "", ""])
            for p in h["open_ports"]:
                w.writerow(base + [p["port"], p["service"], p["banner"]])


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="nemla",
        description="Nemla (نملة) - lightweight network reconnaissance tool",
        epilog="Only scan systems you own or have explicit permission to test.",
    )
    p.add_argument("-t", "--target", required=True,
                   help="IP, hostname, CIDR (10.0.0.0/24), range (10.0.0.1-50 or 10.0.0.1-10.0.0.50)")
    p.add_argument("-p", "--ports", help="ports: 22 | 22,80,443 | 1-1000")
    p.add_argument("--top-ports", action="store_true",
                   help="scan the common-ports list (default when -p is not given)")
    p.add_argument("-o", "--output", default="nemla_report.html", help="HTML report path")
    p.add_argument("--json", metavar="FILE", help="also write results as JSON")
    p.add_argument("--csv", metavar="FILE", help="also write results as CSV")
    p.add_argument("--no-os", action="store_true", help="skip OS fingerprinting")
    p.add_argument("--no-ping", action="store_true",
                   help="skip host discovery, treat every target as up (like nmap -Pn)")
    p.add_argument("--no-banner", action="store_true", help="skip banner grabbing")
    p.add_argument("--threads", type=int, default=150, help="worker threads (default 150)")
    p.add_argument("--timeout", type=float, default=0.7,
                   help="TCP connect timeout in seconds (default 0.7)")
    p.add_argument("--max-hosts", type=int, default=1024,
                   help="refuse targets larger than this many addresses (default 1024)")
    p.add_argument("--lang", choices=sorted(STRINGS), default="en",
                   help="interface and report language (default en)")
    p.add_argument("--version", action="version", version=f"nemla {__version__}")
    return p


def main(argv=None) -> int:
    global _LANG
    args = build_parser().parse_args(argv)
    _LANG = args.lang
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass
    print_banner()

    try:
        ips = parse_targets(args.target, args.max_hosts)
    except ValueError as err:
        log(t("invalid_target", err=err))
        return 1

    try:
        ports = set(parse_ports(args.ports)) if args.ports else set()
    except ValueError as err:
        log(t("invalid_ports", err=err))
        return 1
    if args.top_ports or not ports:
        ports |= set(TOP_PORTS)
    ports = sorted(ports)
    threads = max(1, args.threads)

    start = time.time()
    if args.no_ping:
        log(t("skip_discovery", n=len(ips)))
        hosts_map = {ip: {"mac": None, "method": "skipped"} for ip in ips}
    else:
        probe_ports = sorted(set(DISCOVERY_PORTS) | set(ports[:15]))
        hosts_map = discover_hosts(ips, workers=threads, probe_ports=probe_ports)
    if not hosts_map:
        log(t("no_hosts"))
        return 0

    log(t("port_count", n=len(ports)))
    hosts = []
    try:
        for ip in sorted(hosts_map, key=lambda x: int(ipaddress.ip_address(x))):
            log(t("scanning", ip=ip))
            open_ports = scan_host_ports(ip, ports, threads, args.timeout,
                                         grab=not args.no_banner)
            ttl = None
            if args.no_os:
                os_guess = t("os_skipped")
            else:
                ttl = get_ttl(ip)
                os_guess = guess_os(ttl, open_ports)
                if ttl:
                    os_guess += f" (TTL={ttl})"
            hosts.append({
                "ip": ip, "mac": hosts_map[ip].get("mac"),
                "discovery": hosts_map[ip].get("method"),
                "os_guess": os_guess, "ttl": ttl, "open_ports": open_ports,
            })
            log(t("host_done", n=len(open_ports), os=os_guess))
    except KeyboardInterrupt:
        log(t("interrupted"))

    meta = {
        "target": args.target,
        "scan_time": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "duration": time.time() - start,
        "ports_scanned": len(ports),
    }
    log(t("done", sec=meta["duration"]))

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(render_html(meta, hosts))
    log(t("saved", kind="HTML", path=args.output))
    if args.json:
        write_json(args.json, meta, hosts)
        log(t("saved", kind="JSON", path=args.json))
    if args.csv:
        write_csv(args.csv, hosts)
        log(t("saved", kind="CSV", path=args.csv))
    return 0


if __name__ == "__main__":
    sys.exit(main())
