"""Translations added in Nemla 2: findings, reports, UDP and ARP notes.

Merged over the original strings by i18n.py. Every language has exactly the
same keys (a test enforces it). `f_*` is the one-line title of a finding,
`fd_*` why it matters and `fr_*` what to do about it.
"""
from __future__ import annotations

EXTRA = {
    "en": {
        # scan notes
        "w_arp_incomplete": "ARP found {arp} of {total} addresses; probing the rest by TCP/ICMP found {extra} more.",
        "udp_start": "Scanning {n} UDP port(s) per host, at most {rate} packets/s",
        "budget_hit": "The probe budget was used up: the scan is incomplete.",
        "os_line": "OS: {os} ({conf}%{est})",
        # report
        "r_exec": "Executive summary",
        "r_exec_text": "{hosts} host(s) on {target}: {open} open port(s). Findings: {high} high, {medium} medium, {low} low.",
        "r_meta": "Scan details",
        "r_os": "System",
        "r_confidence": "Confidence",
        "r_evidence": "Evidence",
        "r_remedy": "How to fix",
        "r_state": "State",
        "r_proto": "Protocol",
        "r_severity": "Severity",
        "r_warnings": "Warnings and errors",
        "r_no_findings": "No findings.",
        "r_no_warnings": "No warnings.",
        "r_udp_unconfirmed": "UDP ports that did not answer (open|filtered)",
        "r_est": "estimated",
        "r_udp_scanned": "UDP ports scanned per host",
        "r_top": "Findings",
        "r_tool": "Tool",
        "r_host": "Host",
        "r_finding": "Finding",
        # finding titles (the old ones live in the original strings)
        "f_tls_not_yet_valid": "The TLS certificate on port {port} is not valid yet.",
        "f_tls_weak_sig": "The TLS certificate on port {port} is signed with a weak algorithm ({alg}).",
        "f_tls_weak_key": "The TLS certificate on port {port} uses a short {keytype} key ({bits} bits).",
        "f_ssh_protocol1": "SSH on port {port} still accepts the obsolete protocol {version}.",
        "f_ssh_weak_crypto": "SSH on port {port} offers weak algorithms: {list}.",
        "f_smb1": "SMBv1 is enabled on port {port}.",
        "f_smb_signing": "SMB signing is not required on port {port}.",
        "f_rdp_no_nla": "RDP on port {port} does not require Network Level Authentication.",
        "f_rdp_weak_security": "RDP on port {port} accepts the legacy standard security layer.",
        "f_dns_recursion": "The DNS server on port {port} advertises recursion.",
        "f_snmp_default": "SNMP on port {port} answers to the default community 'public'.",
        "f_admin_panel": "An administration console ({name}) is reachable on port {port}.",
        "f_basic_auth_plain": "The web server on port {port} asks for a Basic-auth password over plain HTTP.",
        "f_smtp_plain_auth": "The mail server on port {port} accepts PLAIN/LOGIN passwords without STARTTLS.",
        "f_smtp_no_starttls": "The mail server on port {port} does not offer STARTTLS.",
        "f_mail_plain": "{service} on port {port} has no STARTTLS: passwords travel in clear text.",
        "f_udp_exposed": "{service} answers from a public address on UDP port {port}.",
        "f_tftp": "A TFTP server answers on UDP port {port}.",
        "f_sensitive_port": "Port {port} is open and is usually {name} (not confirmed).",
        # why it matters
        "fd_telnet": "Telnet sends the login and everything typed in clear text, so anyone on the path can read passwords.",
        "fd_ftp": "Plain FTP sends passwords and files unencrypted.",
        "fd_remote": "Remote-access services are a common target for password guessing and stolen credentials when other machines can reach them.",
        "fd_db": "Databases should normally only be reachable from the application servers that use them.",
        "fd_files": "File-sharing and RPC services expose users and shares and, when misconfigured, data.",
        "fd_redis_open": "Anyone who can connect can read and change every key, and often run commands on the host.",
        "fd_memcached": "Memcached has no login: an open instance leaks cached data and can be abused to amplify attack traffic.",
        "fd_es_open": "Without a login anyone can read, change and delete every index.",
        "fd_http_plain": "The site is only offered over plain HTTP, so visitors' traffic can be read or altered on the way.",
        "fd_tls_expired": "Clients reject an expired certificate, and attackers can more easily pass off a fake one.",
        "fd_tls_expiring": "The certificate stops being valid soon; once it lapses clients will show errors.",
        "fd_tls_old": "TLS 1.0 and 1.1 have known weaknesses and are deprecated.",
        "fd_tls_selfsigned": "Clients cannot verify who they are talking to, so users learn to click through warnings.",
        "fd_version": "Exact version numbers help attackers pick matching exploits.",
        "fd_tls_not_yet_valid": "The certificate's start date is in the future (or the server clock is wrong).",
        "fd_tls_weak_sig": "MD5 and SHA-1 signatures can be forged and are rejected by modern clients.",
        "fd_tls_weak_key": "Keys shorter than 2048 bits can be broken with modest resources.",
        "fd_ssh_protocol1": "SSH protocol 1 has serious cryptographic flaws.",
        "fd_ssh_weak_crypto": "Old ciphers, MACs and key exchanges weaken the encrypted channel.",
        "fd_smb1": "SMBv1 is obsolete and was the entry point of worms such as WannaCry.",
        "fd_smb_signing": "Without required signing, SMB traffic can be relayed or tampered with.",
        "fd_rdp_no_nla": "Without NLA the login screen is open to unauthenticated users, brute force and denial of service.",
        "fd_rdp_weak_security": "Legacy RDP security has weak encryption and does not authenticate the server.",
        "fd_dns_recursion": "A server that resolves names for anyone can be abused for amplification attacks (an open resolver). The flag alone does not prove that strangers are answered.",
        "fd_snmp_default": "It reveals system details and, with a writable community, can allow changes.",
        "fd_admin_panel": "Administration consoles are prime targets for password guessing and known exploits.",
        "fd_basic_auth_plain": "Basic authentication only encodes the password; without TLS anyone on the path can read it.",
        "fd_smtp_plain_auth": "Passwords sent that way travel in clear text.",
        "fd_smtp_no_starttls": "Mail exchanged with it can be read on the network.",
        "fd_mail_plain": "Mailbox passwords and messages can be read on the network.",
        "fd_udp_exposed": "UDP services that answer strangers can be abused to amplify attack traffic.",
        "fd_tftp": "TFTP has no authentication: files (often device configurations) can be read or written by anyone who can reach it.",
        "fd_sensitive_port": "This kind of service is powerful and is often left without authentication by default.",
        # what to do
        "fr_telnet": "Disable Telnet and use SSH instead.",
        "fr_ftp": "Use SFTP or FTPS, or restrict FTP to a trusted network.",
        "fr_remote": "Restrict it to a VPN or trusted addresses and require strong authentication.",
        "fr_db": "Bind it to localhost or a private interface and firewall the port.",
        "fr_files": "Block it at the firewall unless it is needed, and never expose it to the internet.",
        "fr_redis_open": "Set requirepass or ACLs, bind to localhost and firewall the port.",
        "fr_memcached": "Bind it to localhost, disable UDP (-U 0) and firewall the port.",
        "fr_es_open": "Enable authentication (security features) and restrict network access.",
        "fr_http_plain": "Serve the site over HTTPS and redirect HTTP to it.",
        "fr_tls_expired": "Renew the certificate now and automate renewal.",
        "fr_tls_expiring": "Renew it before it expires and automate renewal.",
        "fr_tls_old": "Allow only TLS 1.2 and TLS 1.3.",
        "fr_tls_selfsigned": "Use a certificate from a trusted CA (or your internal CA, distributed to clients).",
        "fr_version": "Hide the version banner if the software allows it, and keep it patched.",
        "fr_tls_not_yet_valid": "Check the server clock and the certificate's validity dates.",
        "fr_tls_weak_sig": "Reissue the certificate with SHA-256 or stronger.",
        "fr_tls_weak_key": "Reissue the certificate with a 2048-bit (or larger) RSA key or an ECDSA key.",
        "fr_ssh_protocol1": "Configure the SSH server for protocol 2 only.",
        "fr_ssh_weak_crypto": "Remove them from the server's Ciphers, MACs and KexAlgorithms settings.",
        "fr_smb1": "Disable SMBv1 and use SMB 2 or 3.",
        "fr_smb_signing": "Require SMB signing (group policy or server configuration).",
        "fr_rdp_no_nla": "Require Network Level Authentication on the RDP host.",
        "fr_rdp_weak_security": "Require TLS/NLA and disable the standard RDP security layer.",
        "fr_dns_recursion": "Restrict recursion to your own networks.",
        "fr_snmp_default": "Change the community strings or move to SNMPv3, and restrict access.",
        "fr_admin_panel": "Restrict it to a management network or VPN and require strong authentication.",
        "fr_basic_auth_plain": "Serve it over HTTPS only.",
        "fr_smtp_plain_auth": "Offer AUTH only after STARTTLS (or over implicit TLS).",
        "fr_smtp_no_starttls": "Enable STARTTLS with a valid certificate.",
        "fr_mail_plain": "Enable STARTTLS or use the TLS ports (IMAPS 993, POP3S 995).",
        "fr_udp_exposed": "Firewall the port or restrict it to known clients.",
        "fr_tftp": "Disable it, or restrict it to the devices that need it.",
        "fr_sensitive_port": "Confirm what runs here; if it is {name}, require authentication and restrict access.",
        # guard: evidence and confidence
        "g_conf_low": "low confidence",
        "g_conf_medium": "medium confidence",
        "g_conf_high": "high confidence",
        "g_evidence": "Evidence: {evidence}",
        "g_arp_change": "{ip} now answers from {new_mac} instead of {old_mac}. This can be ARP spoofing, but it is also what a replaced network card, a DHCP change or a virtual machine looks like.",
        "g_arp_gateway": "The gateway {ip} now answers from {new_mac} instead of {old_mac}. This is a possible sign of ARP spoofing; check whether the router was replaced or restarted.",
        "g_arp_dup": "{mac} answers for several addresses including the gateway {ip}: {ips}. This can be ARP spoofing, or a router doing proxy ARP.",
    },
    "ar": {
        "w_arp_incomplete": "وجد ARP ‏{arp} من أصل {total} عنوان؛ وفحص الباقي عبر TCP/ICMP وجد {extra} إضافياً.",
        "udp_start": "فحص {n} منفذ UDP لكل جهاز، بحد أقصى {rate} حزمة/ثانية",
        "budget_hit": "استُنفدت ميزانية الفحوصات: الفحص غير مكتمل.",
        "os_line": "النظام: {os} ({conf}%{est})",
        "r_exec": "الملخص التنفيذي",
        "r_exec_text": "{hosts} جهاز على {target}: {open} منفذ مفتوح. النتائج: {high} عالية، {medium} متوسطة، {low} منخفضة.",
        "r_meta": "تفاصيل الفحص",
        "r_os": "النظام",
        "r_confidence": "الثقة",
        "r_evidence": "الدليل",
        "r_remedy": "طريقة الإصلاح",
        "r_state": "الحالة",
        "r_proto": "البروتوكول",
        "r_severity": "الخطورة",
        "r_warnings": "التحذيرات والأخطاء",
        "r_no_findings": "لا توجد نتائج.",
        "r_no_warnings": "لا توجد تحذيرات.",
        "r_udp_unconfirmed": "منافذ UDP التي لم تردّ (open|filtered)",
        "r_est": "تقديري",
        "r_udp_scanned": "منافذ UDP المفحوصة لكل جهاز",
        "r_top": "النتائج",
        "r_tool": "الأداة",
        "r_host": "الجهاز",
        "r_finding": "النتيجة",
        "f_tls_not_yet_valid": "شهادة TLS على المنفذ {port} لم تبدأ صلاحيتها بعد.",
        "f_tls_weak_sig": "شهادة TLS على المنفذ {port} موقّعة بخوارزمية ضعيفة ({alg}).",
        "f_tls_weak_key": "شهادة TLS على المنفذ {port} تستخدم مفتاح {keytype} قصيراً ({bits} بت).",
        "f_ssh_protocol1": "خدمة SSH على المنفذ {port} ما زالت تقبل البروتوكول القديم {version}.",
        "f_ssh_weak_crypto": "خدمة SSH على المنفذ {port} تعرض خوارزميات ضعيفة: {list}.",
        "f_smb1": "بروتوكول SMBv1 مفعّل على المنفذ {port}.",
        "f_smb_signing": "توقيع SMB غير مطلوب على المنفذ {port}.",
        "f_rdp_no_nla": "خدمة RDP على المنفذ {port} لا تشترط مصادقة مستوى الشبكة (NLA).",
        "f_rdp_weak_security": "خدمة RDP على المنفذ {port} تقبل طبقة الأمان القياسية القديمة.",
        "f_dns_recursion": "خادم DNS على المنفذ {port} يعلن دعم الاستعلام التكراري (recursion).",
        "f_snmp_default": "خدمة SNMP على المنفذ {port} تردّ على مجموعة المجتمع الافتراضية 'public'.",
        "f_admin_panel": "لوحة إدارة ({name}) متاحة على المنفذ {port}.",
        "f_basic_auth_plain": "خادم الويب على المنفذ {port} يطلب كلمة مرور Basic عبر HTTP غير مشفّر.",
        "f_smtp_plain_auth": "خادم البريد على المنفذ {port} يقبل كلمات مرور PLAIN/LOGIN دون STARTTLS.",
        "f_smtp_no_starttls": "خادم البريد على المنفذ {port} لا يعرض STARTTLS.",
        "f_mail_plain": "خدمة {service} على المنفذ {port} بلا STARTTLS: كلمات المرور تُرسل كنص واضح.",
        "f_udp_exposed": "خدمة {service} تردّ من عنوان عام على منفذ UDP ‏{port}.",
        "f_tftp": "خادم TFTP يردّ على منفذ UDP ‏{port}.",
        "f_sensitive_port": "المنفذ {port} مفتوح وهو عادةً {name} (لم يتم التأكد).",
        "fd_telnet": "يرسل Telnet بيانات الدخول وكل ما يُكتب كنص واضح، فيستطيع أي طرف على المسار قراءة كلمات المرور.",
        "fd_ftp": "يرسل FTP العادي كلمات المرور والملفات دون تشفير.",
        "fd_remote": "خدمات الوصول عن بُعد هدف شائع لتخمين كلمات المرور وسرقة بيانات الدخول عندما تصل إليها أجهزة أخرى.",
        "fd_db": "يجب أن تكون قواعد البيانات متاحة عادةً لخوادم التطبيقات التي تستخدمها فقط.",
        "fd_files": "تكشف خدمات مشاركة الملفات وRPC عن المستخدمين والمشاركات، وعن البيانات عند سوء الإعداد.",
        "fd_redis_open": "يستطيع أي شخص يتصل قراءة كل المفاتيح وتعديلها، وغالباً تنفيذ أوامر على الجهاز.",
        "fd_memcached": "لا يملك Memcached تسجيل دخول: النسخة المفتوحة تسرّب البيانات المخزّنة ويمكن استغلالها لتضخيم حركة الهجمات.",
        "fd_es_open": "دون تسجيل دخول يستطيع أي شخص قراءة كل الفهارس وتعديلها وحذفها.",
        "fd_http_plain": "الموقع متاح عبر HTTP العادي فقط، فيمكن قراءة حركة الزوار أو تعديلها في الطريق.",
        "fd_tls_expired": "ترفض العملاء الشهادة المنتهية، ويسهل على المهاجمين تمرير شهادة مزيفة.",
        "fd_tls_expiring": "ستنتهي صلاحية الشهادة قريباً، وبعد انتهائها ستظهر أخطاء لدى العملاء.",
        "fd_tls_old": "لدى TLS 1.0 و1.1 نقاط ضعف معروفة وقد أُوقف العمل بهما.",
        "fd_tls_selfsigned": "لا يستطيع العملاء التحقق ممّن يتحدثون إليه، فيعتاد المستخدمون تجاوز التحذيرات.",
        "fd_version": "تساعد أرقام الإصدارات الدقيقة المهاجمين على اختيار ثغرات مناسبة.",
        "fd_tls_not_yet_valid": "تاريخ بداية الشهادة في المستقبل (أو أن ساعة الخادم خاطئة).",
        "fd_tls_weak_sig": "يمكن تزوير توقيعات MD5 وSHA-1 وترفضها العملاء الحديثة.",
        "fd_tls_weak_key": "يمكن كسر المفاتيح الأقصر من 2048 بت بموارد متواضعة.",
        "fd_ssh_protocol1": "بروتوكول SSH 1 فيه عيوب تشفير خطيرة.",
        "fd_ssh_weak_crypto": "الخوارزميات القديمة للتشفير وMAC وتبادل المفاتيح تُضعف القناة المشفرة.",
        "fd_smb1": "SMBv1 قديم وكان بوابة دخول ديدان مثل WannaCry.",
        "fd_smb_signing": "دون توقيع مطلوب يمكن إعادة توجيه حركة SMB أو العبث بها.",
        "fd_rdp_no_nla": "دون NLA تكون شاشة الدخول مفتوحة لمستخدمين غير موثَّقين ولهجمات التخمين وحجب الخدمة.",
        "fd_rdp_weak_security": "أمان RDP القديم تشفيره ضعيف ولا يوثّق الخادم.",
        "fd_dns_recursion": "الخادم الذي يحلّ الأسماء لأي شخص يمكن استغلاله في هجمات التضخيم (resolver مفتوح). العلامة وحدها لا تثبت أنه يردّ على الغرباء.",
        "fd_snmp_default": "تكشف تفاصيل النظام، ومع مجموعة قابلة للكتابة قد تسمح بالتعديل.",
        "fd_admin_panel": "لوحات الإدارة أهداف رئيسية لتخمين كلمات المرور والثغرات المعروفة.",
        "fd_basic_auth_plain": "المصادقة الأساسية تُرمّز كلمة المرور فقط؛ دون TLS يستطيع أي طرف على المسار قراءتها.",
        "fd_smtp_plain_auth": "كلمات المرور المرسلة بهذه الطريقة تنتقل كنص واضح.",
        "fd_smtp_no_starttls": "يمكن قراءة البريد المتبادل معه على الشبكة.",
        "fd_mail_plain": "يمكن قراءة كلمات مرور صندوق البريد والرسائل على الشبكة.",
        "fd_udp_exposed": "خدمات UDP التي تردّ على الغرباء يمكن استغلالها لتضخيم حركة الهجمات.",
        "fd_tftp": "لا يملك TFTP مصادقة: يستطيع أي شخص يصل إليه قراءة الملفات (وغالباً إعدادات الأجهزة) أو كتابتها.",
        "fd_sensitive_port": "هذا النوع من الخدمات قوي وغالباً يُترك دون مصادقة افتراضياً.",
        "fr_telnet": "عطّل Telnet واستخدم SSH بدلاً منه.",
        "fr_ftp": "استخدم SFTP أو FTPS، أو احصر FTP في شبكة موثوقة.",
        "fr_remote": "احصرها في VPN أو عناوين موثوقة واشترط مصادقة قوية.",
        "fr_db": "اربطها بـ localhost أو بواجهة خاصة وأغلق المنفذ بالجدار الناري.",
        "fr_files": "احجبها في الجدار الناري إلا عند الحاجة، ولا تعرضها للإنترنت أبداً.",
        "fr_redis_open": "فعّل requirepass أو ACL واربطه بـ localhost وأغلق المنفذ.",
        "fr_memcached": "اربطه بـ localhost وعطّل UDP (‏-U 0) وأغلق المنفذ.",
        "fr_es_open": "فعّل المصادقة (ميزات الأمان) وقيّد الوصول من الشبكة.",
        "fr_http_plain": "قدّم الموقع عبر HTTPS وأعد توجيه HTTP إليه.",
        "fr_tls_expired": "جدّد الشهادة الآن وأتمت التجديد.",
        "fr_tls_expiring": "جدّدها قبل انتهاء صلاحيتها وأتمت التجديد.",
        "fr_tls_old": "اسمح بـ TLS 1.2 وTLS 1.3 فقط.",
        "fr_tls_selfsigned": "استخدم شهادة من جهة موثوقة (أو من جهة إصدار داخلية موزّعة على العملاء).",
        "fr_version": "أخفِ لافتة الإصدار إن أتاح البرنامج ذلك، وحدّثه باستمرار.",
        "fr_tls_not_yet_valid": "تحقق من ساعة الخادم ومن تواريخ صلاحية الشهادة.",
        "fr_tls_weak_sig": "أعد إصدار الشهادة بتوقيع SHA-256 أو أقوى.",
        "fr_tls_weak_key": "أعد إصدار الشهادة بمفتاح RSA بطول 2048 بت (أو أكبر) أو بمفتاح ECDSA.",
        "fr_ssh_protocol1": "اضبط خادم SSH على البروتوكول 2 فقط.",
        "fr_ssh_weak_crypto": "أزلها من إعدادات Ciphers وMACs وKexAlgorithms في الخادم.",
        "fr_smb1": "عطّل SMBv1 واستخدم SMB 2 أو 3.",
        "fr_smb_signing": "اشترط توقيع SMB (من سياسة المجموعة أو إعدادات الخادم).",
        "fr_rdp_no_nla": "اشترط مصادقة مستوى الشبكة (NLA) على جهاز RDP.",
        "fr_rdp_weak_security": "اشترط TLS/NLA وعطّل طبقة أمان RDP القياسية.",
        "fr_dns_recursion": "احصر الاستعلام التكراري في شبكاتك أنت.",
        "fr_snmp_default": "غيّر مجموعات المجتمع أو انتقل إلى SNMPv3 وقيّد الوصول.",
        "fr_admin_panel": "احصرها في شبكة إدارة أو VPN واشترط مصادقة قوية.",
        "fr_basic_auth_plain": "قدّمها عبر HTTPS فقط.",
        "fr_smtp_plain_auth": "اعرض AUTH بعد STARTTLS فقط (أو عبر TLS الضمني).",
        "fr_smtp_no_starttls": "فعّل STARTTLS بشهادة صالحة.",
        "fr_mail_plain": "فعّل STARTTLS أو استخدم منافذ TLS (‏IMAPS 993 وPOP3S 995).",
        "fr_udp_exposed": "أغلق المنفذ بالجدار الناري أو احصره في عملاء معروفين.",
        "fr_tftp": "عطّله أو احصره في الأجهزة التي تحتاجه.",
        "fr_sensitive_port": "تأكد مما يعمل هنا؛ وإذا كان {name} فاشترط المصادقة وقيّد الوصول.",
        "g_conf_low": "ثقة منخفضة",
        "g_conf_medium": "ثقة متوسطة",
        "g_conf_high": "ثقة عالية",
        "g_evidence": "الدليل: {evidence}",
        "g_arp_change": "{ip} صار يردّ من {new_mac} بدل {old_mac}. قد يكون هذا انتحال ARP، لكنه أيضاً ما يظهر عند استبدال كرت الشبكة أو تغيّر DHCP أو وجود جهاز افتراضي.",
        "g_arp_gateway": "بوابة الشبكة {ip} صارت تردّ من {new_mac} بدل {old_mac}. هذه علامة محتملة على انتحال ARP؛ تحقق هل تم استبدال الراوتر أو إعادة تشغيله.",
        "g_arp_dup": "{mac} يردّ عن عدة عناوين منها البوابة {ip}: {ips}. قد يكون هذا انتحال ARP، أو راوتر يعمل بـ proxy ARP.",
    },
    "he": {
        "w_arp_incomplete": "ARP מצא {arp} מתוך {total} כתובות; בדיקת השאר ב-TCP/ICMP מצאה עוד {extra}.",
        "udp_start": "סורק {n} פורטי UDP לכל מארח, לכל היותר {rate} חבילות בשנייה",
        "budget_hit": "תקציב הבדיקות אזל: הסריקה לא הושלמה.",
        "os_line": "מערכת: {os} ({conf}%{est})",
        "r_exec": "תקציר מנהלים",
        "r_exec_text": "{hosts} מארחים ב-{target}: {open} פורטים פתוחים. ממצאים: {high} גבוהים, {medium} בינוניים, {low} נמוכים.",
        "r_meta": "פרטי הסריקה",
        "r_os": "מערכת",
        "r_confidence": "רמת ביטחון",
        "r_evidence": "ראיה",
        "r_remedy": "איך לתקן",
        "r_state": "מצב",
        "r_proto": "פרוטוקול",
        "r_severity": "חומרה",
        "r_warnings": "אזהרות ושגיאות",
        "r_no_findings": "אין ממצאים.",
        "r_no_warnings": "אין אזהרות.",
        "r_udp_unconfirmed": "פורטי UDP שלא ענו (open|filtered)",
        "r_est": "משוער",
        "r_udp_scanned": "פורטי UDP שנסרקו לכל מארח",
        "r_top": "ממצאים",
        "r_tool": "כלי",
        "r_host": "מארח",
        "r_finding": "ממצא",
        "f_tls_not_yet_valid": "תעודת ה-TLS בפורט {port} עדיין לא בתוקף.",
        "f_tls_weak_sig": "תעודת ה-TLS בפורט {port} חתומה באלגוריתם חלש ({alg}).",
        "f_tls_weak_key": "תעודת ה-TLS בפורט {port} משתמשת במפתח {keytype} קצר ({bits} ביט).",
        "f_ssh_protocol1": "SSH בפורט {port} עדיין מקבל את הפרוטוקול המיושן {version}.",
        "f_ssh_weak_crypto": "SSH בפורט {port} מציע אלגוריתמים חלשים: {list}.",
        "f_smb1": "SMBv1 מופעל בפורט {port}.",
        "f_smb_signing": "חתימת SMB אינה נדרשת בפורט {port}.",
        "f_rdp_no_nla": "RDP בפורט {port} אינו דורש אימות ברמת הרשת (NLA).",
        "f_rdp_weak_security": "RDP בפורט {port} מקבל את שכבת האבטחה הסטנדרטית הישנה.",
        "f_dns_recursion": "שרת ה-DNS בפורט {port} מפרסם תמיכה ברקורסיה.",
        "f_snmp_default": "SNMP בפורט {port} עונה לקהילת ברירת המחדל 'public'.",
        "f_admin_panel": "קונסולת ניהול ({name}) נגישה בפורט {port}.",
        "f_basic_auth_plain": "שרת האינטרנט בפורט {port} מבקש סיסמת Basic דרך HTTP לא מוצפן.",
        "f_smtp_plain_auth": "שרת הדואר בפורט {port} מקבל סיסמאות PLAIN/LOGIN ללא STARTTLS.",
        "f_smtp_no_starttls": "שרת הדואר בפורט {port} אינו מציע STARTTLS.",
        "f_mail_plain": "{service} בפורט {port} ללא STARTTLS: הסיסמאות עוברות כטקסט גלוי.",
        "f_udp_exposed": "{service} עונה מכתובת ציבורית בפורט UDP {port}.",
        "f_tftp": "שרת TFTP עונה בפורט UDP {port}.",
        "f_sensitive_port": "פורט {port} פתוח ולרוב זה {name} (לא אומת).",
        "fd_telnet": "Telnet שולח את פרטי הכניסה וכל מה שמוקלד כטקסט גלוי, ולכן כל מי שנמצא בדרך יכול לקרוא סיסמאות.",
        "fd_ftp": "FTP רגיל שולח סיסמאות וקבצים ללא הצפנה.",
        "fd_remote": "שירותי גישה מרחוק הם יעד נפוץ לניחוש סיסמאות ולגניבת פרטי כניסה כשמחשבים אחרים יכולים להגיע אליהם.",
        "fd_db": "בדרך כלל מסדי נתונים צריכים להיות נגישים רק משרתי היישומים שמשתמשים בהם.",
        "fd_files": "שירותי שיתוף קבצים ו-RPC חושפים משתמשים ושיתופים, ואת הנתונים עצמם כשההגדרה שגויה.",
        "fd_redis_open": "כל מי שמתחבר יכול לקרוא ולשנות כל מפתח, ולעיתים גם להריץ פקודות על המחשב.",
        "fd_memcached": "ל-Memcached אין הזדהות: מופע פתוח מדליף נתונים שמורים וניתן לנצל אותו להגברת תעבורת התקפה.",
        "fd_es_open": "ללא הזדהות כל אחד יכול לקרוא, לשנות ולמחוק כל אינדקס.",
        "fd_http_plain": "האתר מוגש רק דרך HTTP רגיל, ולכן ניתן לקרוא או לשנות את תעבורת המבקרים בדרך.",
        "fd_tls_expired": "לקוחות דוחים תעודה שפג תוקפה, ותוקפים יכולים בקלות רבה יותר להציג תעודה מזויפת.",
        "fd_tls_expiring": "תוקף התעודה יפוג בקרוב, ואחרי שיפוג הלקוחות יציגו שגיאות.",
        "fd_tls_old": "ל-TLS 1.0 ו-1.1 יש חולשות ידועות והם הוצאו משימוש.",
        "fd_tls_selfsigned": "הלקוחות לא יכולים לוודא עם מי הם מדברים, והמשתמשים לומדים להתעלם מאזהרות.",
        "fd_version": "מספרי גרסה מדויקים עוזרים לתוקפים לבחור פרצות מתאימות.",
        "fd_tls_not_yet_valid": "תאריך ההתחלה של התעודה בעתיד (או שהשעון בשרת שגוי).",
        "fd_tls_weak_sig": "אפשר לזייף חתימות MD5 ו-SHA-1 ולקוחות מודרניים דוחים אותן.",
        "fd_tls_weak_key": "אפשר לשבור מפתחות קצרים מ-2048 ביט במשאבים צנועים.",
        "fd_ssh_protocol1": "לפרוטוקול SSH 1 יש פגמי הצפנה חמורים.",
        "fd_ssh_weak_crypto": "צפנים, MAC והחלפות מפתחות ישנים מחלישים את הערוץ המוצפן.",
        "fd_smb1": "SMBv1 מיושן והיה נקודת הכניסה של תולעים כמו WannaCry.",
        "fd_smb_signing": "בלי חתימה נדרשת אפשר להעביר הלאה או לשבש תעבורת SMB.",
        "fd_rdp_no_nla": "בלי NLA מסך הכניסה פתוח למשתמשים לא מאומתים, לניחוש סיסמאות ולמניעת שירות.",
        "fd_rdp_weak_security": "לאבטחת RDP הישנה הצפנה חלשה והיא אינה מאמתת את השרת.",
        "fd_dns_recursion": "שרת שפותר שמות לכל אחד ניתן לניצול בהתקפות הגברה (פותר פתוח). הדגל לבדו אינו מוכיח שהוא עונה לזרים.",
        "fd_snmp_default": "היא חושפת פרטי מערכת, ועם קהילה ניתנת לכתיבה עלולה לאפשר שינויים.",
        "fd_admin_panel": "קונסולות ניהול הן יעד מרכזי לניחוש סיסמאות ולפרצות ידועות.",
        "fd_basic_auth_plain": "אימות Basic רק מקודד את הסיסמה; בלי TLS כל מי שנמצא בדרך יכול לקרוא אותה.",
        "fd_smtp_plain_auth": "סיסמאות שנשלחות כך עוברות כטקסט גלוי.",
        "fd_smtp_no_starttls": "אפשר לקרוא ברשת דואר שמוחלף איתו.",
        "fd_mail_plain": "אפשר לקרוא ברשת סיסמאות תיבת דואר והודעות.",
        "fd_udp_exposed": "שירותי UDP שעונים לזרים ניתנים לניצול להגברת תעבורת התקפה.",
        "fd_tftp": "ל-TFTP אין אימות: כל מי שמגיע אליו יכול לקרוא או לכתוב קבצים (לרוב הגדרות התקנים).",
        "fd_sensitive_port": "שירות מסוג זה עוצמתי ולעיתים קרובות נשאר ללא אימות כברירת מחדל.",
        "fr_telnet": "בטלו את Telnet והשתמשו ב-SSH במקומו.",
        "fr_ftp": "השתמשו ב-SFTP או ב-FTPS, או הגבילו את FTP לרשת מהימנה.",
        "fr_remote": "הגבילו אותה ל-VPN או לכתובות מהימנות ודרשו אימות חזק.",
        "fr_db": "קשרו אותה ל-localhost או לממשק פרטי וחסמו את הפורט בחומת אש.",
        "fr_files": "חסמו אותה בחומת האש אלא אם היא נחוצה, ולעולם אל תחשפו אותה לאינטרנט.",
        "fr_redis_open": "הגדירו requirepass או ACL, קשרו ל-localhost וחסמו את הפורט.",
        "fr_memcached": "קשרו אותו ל-localhost, בטלו את UDP (‏-U 0) וחסמו את הפורט.",
        "fr_es_open": "הפעילו אימות (תכונות אבטחה) והגבילו את הגישה מהרשת.",
        "fr_http_plain": "הגישו את האתר דרך HTTPS והפנו אליו את HTTP.",
        "fr_tls_expired": "חדשו את התעודה עכשיו ואוטמטו את החידוש.",
        "fr_tls_expiring": "חדשו אותה לפני שתפוג ואוטמטו את החידוש.",
        "fr_tls_old": "אפשרו רק TLS 1.2 ו-TLS 1.3.",
        "fr_tls_selfsigned": "השתמשו בתעודה מרשות מהימנה (או מרשות פנימית שמופצת ללקוחות).",
        "fr_version": "הסתירו את שלט הגרסה אם התוכנה מאפשרת, ושמרו עליה מעודכנת.",
        "fr_tls_not_yet_valid": "בדקו את השעון בשרת ואת תאריכי התוקף של התעודה.",
        "fr_tls_weak_sig": "הנפיקו מחדש את התעודה עם SHA-256 או חזק יותר.",
        "fr_tls_weak_key": "הנפיקו מחדש את התעודה עם מפתח RSA של 2048 ביט (או יותר) או עם מפתח ECDSA.",
        "fr_ssh_protocol1": "הגדירו את שרת ה-SSH לפרוטוקול 2 בלבד.",
        "fr_ssh_weak_crypto": "הסירו אותם מהגדרות Ciphers, MACs ו-KexAlgorithms בשרת.",
        "fr_smb1": "בטלו את SMBv1 והשתמשו ב-SMB 2 או 3.",
        "fr_smb_signing": "דרשו חתימת SMB (מדיניות קבוצה או הגדרות השרת).",
        "fr_rdp_no_nla": "דרשו אימות ברמת הרשת (NLA) במארח ה-RDP.",
        "fr_rdp_weak_security": "דרשו TLS/NLA ובטלו את שכבת האבטחה הסטנדרטית של RDP.",
        "fr_dns_recursion": "הגבילו את הרקורסיה לרשתות שלכם.",
        "fr_snmp_default": "שנו את מחרוזות הקהילה או עברו ל-SNMPv3, והגבילו את הגישה.",
        "fr_admin_panel": "הגבילו אותה לרשת ניהול או ל-VPN ודרשו אימות חזק.",
        "fr_basic_auth_plain": "הגישו אותה דרך HTTPS בלבד.",
        "fr_smtp_plain_auth": "הציעו AUTH רק אחרי STARTTLS (או דרך TLS מרומז).",
        "fr_smtp_no_starttls": "הפעילו STARTTLS עם תעודה תקפה.",
        "fr_mail_plain": "הפעילו STARTTLS או השתמשו בפורטי TLS (‏IMAPS 993, POP3S 995).",
        "fr_udp_exposed": "חסמו את הפורט בחומת אש או הגבילו אותו ללקוחות מוכרים.",
        "fr_tftp": "בטלו אותו או הגבילו אותו להתקנים שזקוקים לו.",
        "fr_sensitive_port": "ודאו מה רץ כאן; אם זה {name}, דרשו אימות והגבילו את הגישה.",
        "g_conf_low": "רמת ביטחון נמוכה",
        "g_conf_medium": "רמת ביטחון בינונית",
        "g_conf_high": "רמת ביטחון גבוהה",
        "g_evidence": "ראיה: {evidence}",
        "g_arp_change": "{ip} עונה כעת מ-{new_mac} במקום {old_mac}. זה עשוי להיות התחזות ARP, אבל כך נראים גם החלפת כרטיס רשת, שינוי DHCP או מכונה וירטואלית.",
        "g_arp_gateway": "שער הרשת {ip} עונה כעת מ-{new_mac} במקום {old_mac}. זה סימן אפשרי להתחזות ARP; בדקו אם הנתב הוחלף או הופעל מחדש.",
        "g_arp_dup": "{mac} עונה עבור כמה כתובות, כולל שער הרשת {ip}: {ips}. זה עשוי להיות התחזות ARP, או נתב שעושה proxy ARP.",
    },
}
